// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: api/player/v1/player.proto

package playerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlayerService_Play_FullMethodName                       = "/player.v1.PlayerService/Play"
	PlayerService_Pause_FullMethodName                      = "/player.v1.PlayerService/Pause"
	PlayerService_Stop_FullMethodName                       = "/player.v1.PlayerService/Stop"
	PlayerService_Next_FullMethodName                       = "/player.v1.PlayerService/Next"
	PlayerService_Previous_FullMethodName                   = "/player.v1.PlayerService/Previous"
	PlayerService_PlayIndex_FullMethodName                  = "/player.v1.PlayerService/PlayIndex"
	PlayerService_Seek_FullMethodName                       = "/player.v1.PlayerService/Seek"
	PlayerService_SetVolume_FullMethodName                  = "/player.v1.PlayerService/SetVolume"
	PlayerService_GetVolume_FullMethodName                  = "/player.v1.PlayerService/GetVolume"
	PlayerService_SetMute_FullMethodName                    = "/player.v1.PlayerService/SetMute"
	PlayerService_GetMute_FullMethodName                    = "/player.v1.PlayerService/GetMute"
	PlayerService_GetQueue_FullMethodName                   = "/player.v1.PlayerService/GetQueue"
	PlayerService_AddToQueue_FullMethodName                 = "/player.v1.PlayerService/AddToQueue"
	PlayerService_RemoveFromQueue_FullMethodName            = "/player.v1.PlayerService/RemoveFromQueue"
	PlayerService_ClearQueue_FullMethodName                 = "/player.v1.PlayerService/ClearQueue"
	PlayerService_LoadPlaylist_FullMethodName               = "/player.v1.PlayerService/LoadPlaylist"
	PlayerService_SavePlaylist_FullMethodName               = "/player.v1.PlayerService/SavePlaylist"
	PlayerService_SetRepeatMode_FullMethodName              = "/player.v1.PlayerService/SetRepeatMode"
	PlayerService_GetRepeatMode_FullMethodName              = "/player.v1.PlayerService/GetRepeatMode"
	PlayerService_SetShuffle_FullMethodName                 = "/player.v1.PlayerService/SetShuffle"
	PlayerService_GetShuffle_FullMethodName                 = "/player.v1.PlayerService/GetShuffle"
	PlayerService_GetStatus_FullMethodName                  = "/player.v1.PlayerService/GetStatus"
	PlayerService_GetCurrentTrack_FullMethodName            = "/player.v1.PlayerService/GetCurrentTrack"
	PlayerService_GetCDDevices_FullMethodName               = "/player.v1.PlayerService/GetCDDevices"
	PlayerService_ReadCD_FullMethodName                     = "/player.v1.PlayerService/ReadCD"
	PlayerService_LoadCD_FullMethodName                     = "/player.v1.PlayerService/LoadCD"
	PlayerService_ListProviders_FullMethodName              = "/player.v1.PlayerService/ListProviders"
	PlayerService_SearchTracks_FullMethodName               = "/player.v1.PlayerService/SearchTracks"
	PlayerService_SearchPlaylists_FullMethodName            = "/player.v1.PlayerService/SearchPlaylists"
	PlayerService_GetProviderTrackDetails_FullMethodName    = "/player.v1.PlayerService/GetProviderTrackDetails"
	PlayerService_ResolveProviderStream_FullMethodName      = "/player.v1.PlayerService/ResolveProviderStream"
	PlayerService_GetProviderPlaylistDetails_FullMethodName = "/player.v1.PlayerService/GetProviderPlaylistDetails"
	PlayerService_AddProviderTrack_FullMethodName           = "/player.v1.PlayerService/AddProviderTrack"
	PlayerService_SubscribeEvents_FullMethodName            = "/player.v1.PlayerService/SubscribeEvents"
)

// PlayerServiceClient is the client API for PlayerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PlayerServiceClient interface {
	// Playback control
	Play(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Next(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Previous(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	PlayIndex(ctx context.Context, in *PlayIndexRequest, opts ...grpc.CallOption) (*Empty, error)
	// Transport
	Seek(ctx context.Context, in *Position, opts ...grpc.CallOption) (*Empty, error)
	SetVolume(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*Empty, error)
	GetVolume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Volume, error)
	SetMute(ctx context.Context, in *Mute, opts ...grpc.CallOption) (*Empty, error)
	GetMute(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Mute, error)
	// Queue / playlist
	GetQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Queue, error)
	AddToQueue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*Empty, error)
	RemoveFromQueue(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	ClearQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	LoadPlaylist(ctx context.Context, in *PlaylistRequest, opts ...grpc.CallOption) (*Empty, error)
	SavePlaylist(ctx context.Context, in *PlaylistRequest, opts ...grpc.CallOption) (*Empty, error)
	// Modes
	SetRepeatMode(ctx context.Context, in *RepeatModeRequest, opts ...grpc.CallOption) (*Empty, error)
	GetRepeatMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RepeatModeRequest, error)
	SetShuffle(ctx context.Context, in *ShuffleRequest, opts ...grpc.CallOption) (*Empty, error)
	GetShuffle(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShuffleRequest, error)
	// Status
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
	GetCurrentTrack(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Track, error)
	// CD
	GetCDDevices(ctx context.Context, in *GetCDDevicesRequest, opts ...grpc.CallOption) (*GetCDDevicesResponse, error)
	ReadCD(ctx context.Context, in *ReadCDRequest, opts ...grpc.CallOption) (*ReadCDResponse, error)
	LoadCD(ctx context.Context, in *LoadCDRequest, opts ...grpc.CallOption) (*Empty, error)
	// Music Provider
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	SearchTracks(ctx context.Context, in *SearchTracksRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error)
	SearchPlaylists(ctx context.Context, in *SearchPlaylistsRequest, opts ...grpc.CallOption) (*SearchPlaylistsResponse, error)
	GetProviderTrackDetails(ctx context.Context, in *ProviderTrackRequest, opts ...grpc.CallOption) (*GetProviderTrackDetailsResponse, error)
	ResolveProviderStream(ctx context.Context, in *ProviderTrackRequest, opts ...grpc.CallOption) (*ResolveProviderStreamResponse, error)
	GetProviderPlaylistDetails(ctx context.Context, in *GetProviderPlaylistDetailsRequest, opts ...grpc.CallOption) (*GetProviderPlaylistDetailsResponse, error)
	AddProviderTrack(ctx context.Context, in *AddProviderTrackRequest, opts ...grpc.CallOption) (*Empty, error)
	// Events
	SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerEvent], error)
}

type playerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlayerServiceClient(cc grpc.ClientConnInterface) PlayerServiceClient {
	return &playerServiceClient{cc}
}

func (c *playerServiceClient) Play(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_Play_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Pause(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_Pause_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Stop(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Next(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_Next_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Previous(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_Previous_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) PlayIndex(ctx context.Context, in *PlayIndexRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_PlayIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) Seek(ctx context.Context, in *Position, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_Seek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SetVolume(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_SetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetVolume(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Volume, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Volume)
	err := c.cc.Invoke(ctx, PlayerService_GetVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SetMute(ctx context.Context, in *Mute, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_SetMute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetMute(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Mute, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Mute)
	err := c.cc.Invoke(ctx, PlayerService_GetMute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Queue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Queue)
	err := c.cc.Invoke(ctx, PlayerService_GetQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) AddToQueue(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_AddToQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) RemoveFromQueue(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_RemoveFromQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ClearQueue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_ClearQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) LoadPlaylist(ctx context.Context, in *PlaylistRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_LoadPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SavePlaylist(ctx context.Context, in *PlaylistRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_SavePlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SetRepeatMode(ctx context.Context, in *RepeatModeRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_SetRepeatMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetRepeatMode(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RepeatModeRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepeatModeRequest)
	err := c.cc.Invoke(ctx, PlayerService_GetRepeatMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SetShuffle(ctx context.Context, in *ShuffleRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_SetShuffle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetShuffle(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ShuffleRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShuffleRequest)
	err := c.cc.Invoke(ctx, PlayerService_GetShuffle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PlayerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetCurrentTrack(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Track, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Track)
	err := c.cc.Invoke(ctx, PlayerService_GetCurrentTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetCDDevices(ctx context.Context, in *GetCDDevicesRequest, opts ...grpc.CallOption) (*GetCDDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCDDevicesResponse)
	err := c.cc.Invoke(ctx, PlayerService_GetCDDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ReadCD(ctx context.Context, in *ReadCDRequest, opts ...grpc.CallOption) (*ReadCDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadCDResponse)
	err := c.cc.Invoke(ctx, PlayerService_ReadCD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) LoadCD(ctx context.Context, in *LoadCDRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_LoadCD_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, PlayerService_ListProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SearchTracks(ctx context.Context, in *SearchTracksRequest, opts ...grpc.CallOption) (*SearchTracksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTracksResponse)
	err := c.cc.Invoke(ctx, PlayerService_SearchTracks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SearchPlaylists(ctx context.Context, in *SearchPlaylistsRequest, opts ...grpc.CallOption) (*SearchPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchPlaylistsResponse)
	err := c.cc.Invoke(ctx, PlayerService_SearchPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetProviderTrackDetails(ctx context.Context, in *ProviderTrackRequest, opts ...grpc.CallOption) (*GetProviderTrackDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderTrackDetailsResponse)
	err := c.cc.Invoke(ctx, PlayerService_GetProviderTrackDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) ResolveProviderStream(ctx context.Context, in *ProviderTrackRequest, opts ...grpc.CallOption) (*ResolveProviderStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveProviderStreamResponse)
	err := c.cc.Invoke(ctx, PlayerService_ResolveProviderStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) GetProviderPlaylistDetails(ctx context.Context, in *GetProviderPlaylistDetailsRequest, opts ...grpc.CallOption) (*GetProviderPlaylistDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderPlaylistDetailsResponse)
	err := c.cc.Invoke(ctx, PlayerService_GetProviderPlaylistDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) AddProviderTrack(ctx context.Context, in *AddProviderTrackRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PlayerService_AddProviderTrack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playerServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PlayerEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PlayerService_ServiceDesc.Streams[0], PlayerService_SubscribeEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, PlayerEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerService_SubscribeEventsClient = grpc.ServerStreamingClient[PlayerEvent]

// PlayerServiceServer is the server API for PlayerService service.
// All implementations must embed UnimplementedPlayerServiceServer
// for forward compatibility.
type PlayerServiceServer interface {
	// Playback control
	Play(context.Context, *Empty) (*Empty, error)
	Pause(context.Context, *Empty) (*Empty, error)
	Stop(context.Context, *Empty) (*Empty, error)
	Next(context.Context, *Empty) (*Empty, error)
	Previous(context.Context, *Empty) (*Empty, error)
	PlayIndex(context.Context, *PlayIndexRequest) (*Empty, error)
	// Transport
	Seek(context.Context, *Position) (*Empty, error)
	SetVolume(context.Context, *Volume) (*Empty, error)
	GetVolume(context.Context, *Empty) (*Volume, error)
	SetMute(context.Context, *Mute) (*Empty, error)
	GetMute(context.Context, *Empty) (*Mute, error)
	// Queue / playlist
	GetQueue(context.Context, *Empty) (*Queue, error)
	AddToQueue(context.Context, *QueueRequest) (*Empty, error)
	RemoveFromQueue(context.Context, *RemoveRequest) (*Empty, error)
	ClearQueue(context.Context, *Empty) (*Empty, error)
	LoadPlaylist(context.Context, *PlaylistRequest) (*Empty, error)
	SavePlaylist(context.Context, *PlaylistRequest) (*Empty, error)
	// Modes
	SetRepeatMode(context.Context, *RepeatModeRequest) (*Empty, error)
	GetRepeatMode(context.Context, *Empty) (*RepeatModeRequest, error)
	SetShuffle(context.Context, *ShuffleRequest) (*Empty, error)
	GetShuffle(context.Context, *Empty) (*ShuffleRequest, error)
	// Status
	GetStatus(context.Context, *Empty) (*Status, error)
	GetCurrentTrack(context.Context, *Empty) (*Track, error)
	// CD
	GetCDDevices(context.Context, *GetCDDevicesRequest) (*GetCDDevicesResponse, error)
	ReadCD(context.Context, *ReadCDRequest) (*ReadCDResponse, error)
	LoadCD(context.Context, *LoadCDRequest) (*Empty, error)
	// Music Provider
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	SearchTracks(context.Context, *SearchTracksRequest) (*SearchTracksResponse, error)
	SearchPlaylists(context.Context, *SearchPlaylistsRequest) (*SearchPlaylistsResponse, error)
	GetProviderTrackDetails(context.Context, *ProviderTrackRequest) (*GetProviderTrackDetailsResponse, error)
	ResolveProviderStream(context.Context, *ProviderTrackRequest) (*ResolveProviderStreamResponse, error)
	GetProviderPlaylistDetails(context.Context, *GetProviderPlaylistDetailsRequest) (*GetProviderPlaylistDetailsResponse, error)
	AddProviderTrack(context.Context, *AddProviderTrackRequest) (*Empty, error)
	// Events
	SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[PlayerEvent]) error
	mustEmbedUnimplementedPlayerServiceServer()
}

// UnimplementedPlayerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlayerServiceServer struct{}

func (UnimplementedPlayerServiceServer) Play(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Play not implemented")
}
func (UnimplementedPlayerServiceServer) Pause(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Pause not implemented")
}
func (UnimplementedPlayerServiceServer) Stop(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedPlayerServiceServer) Next(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedPlayerServiceServer) Previous(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Previous not implemented")
}
func (UnimplementedPlayerServiceServer) PlayIndex(context.Context, *PlayIndexRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayIndex not implemented")
}
func (UnimplementedPlayerServiceServer) Seek(context.Context, *Position) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Seek not implemented")
}
func (UnimplementedPlayerServiceServer) SetVolume(context.Context, *Volume) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetVolume not implemented")
}
func (UnimplementedPlayerServiceServer) GetVolume(context.Context, *Empty) (*Volume, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVolume not implemented")
}
func (UnimplementedPlayerServiceServer) SetMute(context.Context, *Mute) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMute not implemented")
}
func (UnimplementedPlayerServiceServer) GetMute(context.Context, *Empty) (*Mute, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMute not implemented")
}
func (UnimplementedPlayerServiceServer) GetQueue(context.Context, *Empty) (*Queue, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueue not implemented")
}
func (UnimplementedPlayerServiceServer) AddToQueue(context.Context, *QueueRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddToQueue not implemented")
}
func (UnimplementedPlayerServiceServer) RemoveFromQueue(context.Context, *RemoveRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveFromQueue not implemented")
}
func (UnimplementedPlayerServiceServer) ClearQueue(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearQueue not implemented")
}
func (UnimplementedPlayerServiceServer) LoadPlaylist(context.Context, *PlaylistRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadPlaylist not implemented")
}
func (UnimplementedPlayerServiceServer) SavePlaylist(context.Context, *PlaylistRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePlaylist not implemented")
}
func (UnimplementedPlayerServiceServer) SetRepeatMode(context.Context, *RepeatModeRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRepeatMode not implemented")
}
func (UnimplementedPlayerServiceServer) GetRepeatMode(context.Context, *Empty) (*RepeatModeRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepeatMode not implemented")
}
func (UnimplementedPlayerServiceServer) SetShuffle(context.Context, *ShuffleRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetShuffle not implemented")
}
func (UnimplementedPlayerServiceServer) GetShuffle(context.Context, *Empty) (*ShuffleRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShuffle not implemented")
}
func (UnimplementedPlayerServiceServer) GetStatus(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPlayerServiceServer) GetCurrentTrack(context.Context, *Empty) (*Track, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentTrack not implemented")
}
func (UnimplementedPlayerServiceServer) GetCDDevices(context.Context, *GetCDDevicesRequest) (*GetCDDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCDDevices not implemented")
}
func (UnimplementedPlayerServiceServer) ReadCD(context.Context, *ReadCDRequest) (*ReadCDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadCD not implemented")
}
func (UnimplementedPlayerServiceServer) LoadCD(context.Context, *LoadCDRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCD not implemented")
}
func (UnimplementedPlayerServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedPlayerServiceServer) SearchTracks(context.Context, *SearchTracksRequest) (*SearchTracksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchTracks not implemented")
}
func (UnimplementedPlayerServiceServer) SearchPlaylists(context.Context, *SearchPlaylistsRequest) (*SearchPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchPlaylists not implemented")
}
func (UnimplementedPlayerServiceServer) GetProviderTrackDetails(context.Context, *ProviderTrackRequest) (*GetProviderTrackDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderTrackDetails not implemented")
}
func (UnimplementedPlayerServiceServer) ResolveProviderStream(context.Context, *ProviderTrackRequest) (*ResolveProviderStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveProviderStream not implemented")
}
func (UnimplementedPlayerServiceServer) GetProviderPlaylistDetails(context.Context, *GetProviderPlaylistDetailsRequest) (*GetProviderPlaylistDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderPlaylistDetails not implemented")
}
func (UnimplementedPlayerServiceServer) AddProviderTrack(context.Context, *AddProviderTrackRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProviderTrack not implemented")
}
func (UnimplementedPlayerServiceServer) SubscribeEvents(*SubscribeRequest, grpc.ServerStreamingServer[PlayerEvent]) error {
	return status.Error(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedPlayerServiceServer) mustEmbedUnimplementedPlayerServiceServer() {}
func (UnimplementedPlayerServiceServer) testEmbeddedByValue()                       {}

// UnsafePlayerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlayerServiceServer will
// result in compilation errors.
type UnsafePlayerServiceServer interface {
	mustEmbedUnimplementedPlayerServiceServer()
}

func RegisterPlayerServiceServer(s grpc.ServiceRegistrar, srv PlayerServiceServer) {
	// If the following call panics, it indicates UnimplementedPlayerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlayerService_ServiceDesc, srv)
}

func _PlayerService_Play_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Play(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Play_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Play(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Pause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Pause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Pause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Pause(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Stop(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Next_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Next(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Previous_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Previous(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Previous_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Previous(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_PlayIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).PlayIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_PlayIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).PlayIndex(ctx, req.(*PlayIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_Seek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Position)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).Seek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_Seek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).Seek(ctx, req.(*Position))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Volume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SetVolume(ctx, req.(*Volume))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetVolume(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SetMute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Mute)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SetMute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SetMute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SetMute(ctx, req.(*Mute))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetMute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetMute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetMute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetMute(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetQueue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_AddToQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).AddToQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_AddToQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).AddToQueue(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_RemoveFromQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).RemoveFromQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_RemoveFromQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).RemoveFromQueue(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ClearQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ClearQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ClearQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ClearQueue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_LoadPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).LoadPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_LoadPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).LoadPlaylist(ctx, req.(*PlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SavePlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SavePlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SavePlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SavePlaylist(ctx, req.(*PlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SetRepeatMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepeatModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SetRepeatMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SetRepeatMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SetRepeatMode(ctx, req.(*RepeatModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetRepeatMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetRepeatMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetRepeatMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetRepeatMode(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SetShuffle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShuffleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SetShuffle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SetShuffle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SetShuffle(ctx, req.(*ShuffleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetShuffle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetShuffle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetShuffle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetShuffle(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetCurrentTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetCurrentTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetCurrentTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetCurrentTrack(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetCDDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCDDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetCDDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetCDDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetCDDevices(ctx, req.(*GetCDDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ReadCD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ReadCD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ReadCD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ReadCD(ctx, req.(*ReadCDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_LoadCD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).LoadCD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_LoadCD_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).LoadCD(ctx, req.(*LoadCDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ListProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SearchTracks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTracksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SearchTracks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SearchTracks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SearchTracks(ctx, req.(*SearchTracksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SearchPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).SearchPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_SearchPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).SearchPlaylists(ctx, req.(*SearchPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetProviderTrackDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetProviderTrackDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetProviderTrackDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetProviderTrackDetails(ctx, req.(*ProviderTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_ResolveProviderStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).ResolveProviderStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_ResolveProviderStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).ResolveProviderStream(ctx, req.(*ProviderTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_GetProviderPlaylistDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderPlaylistDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).GetProviderPlaylistDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_GetProviderPlaylistDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).GetProviderPlaylistDetails(ctx, req.(*GetProviderPlaylistDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_AddProviderTrack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProviderTrackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayerServiceServer).AddProviderTrack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlayerService_AddProviderTrack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayerServiceServer).AddProviderTrack(ctx, req.(*AddProviderTrackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlayerService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlayerServiceServer).SubscribeEvents(m, &grpc.GenericServerStream[SubscribeRequest, PlayerEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PlayerService_SubscribeEventsServer = grpc.ServerStreamingServer[PlayerEvent]

// PlayerService_ServiceDesc is the grpc.ServiceDesc for PlayerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlayerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "player.v1.PlayerService",
	HandlerType: (*PlayerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Play",
			Handler:    _PlayerService_Play_Handler,
		},
		{
			MethodName: "Pause",
			Handler:    _PlayerService_Pause_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _PlayerService_Stop_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _PlayerService_Next_Handler,
		},
		{
			MethodName: "Previous",
			Handler:    _PlayerService_Previous_Handler,
		},
		{
			MethodName: "PlayIndex",
			Handler:    _PlayerService_PlayIndex_Handler,
		},
		{
			MethodName: "Seek",
			Handler:    _PlayerService_Seek_Handler,
		},
		{
			MethodName: "SetVolume",
			Handler:    _PlayerService_SetVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _PlayerService_GetVolume_Handler,
		},
		{
			MethodName: "SetMute",
			Handler:    _PlayerService_SetMute_Handler,
		},
		{
			MethodName: "GetMute",
			Handler:    _PlayerService_GetMute_Handler,
		},
		{
			MethodName: "GetQueue",
			Handler:    _PlayerService_GetQueue_Handler,
		},
		{
			MethodName: "AddToQueue",
			Handler:    _PlayerService_AddToQueue_Handler,
		},
		{
			MethodName: "RemoveFromQueue",
			Handler:    _PlayerService_RemoveFromQueue_Handler,
		},
		{
			MethodName: "ClearQueue",
			Handler:    _PlayerService_ClearQueue_Handler,
		},
		{
			MethodName: "LoadPlaylist",
			Handler:    _PlayerService_LoadPlaylist_Handler,
		},
		{
			MethodName: "SavePlaylist",
			Handler:    _PlayerService_SavePlaylist_Handler,
		},
		{
			MethodName: "SetRepeatMode",
			Handler:    _PlayerService_SetRepeatMode_Handler,
		},
		{
			MethodName: "GetRepeatMode",
			Handler:    _PlayerService_GetRepeatMode_Handler,
		},
		{
			MethodName: "SetShuffle",
			Handler:    _PlayerService_SetShuffle_Handler,
		},
		{
			MethodName: "GetShuffle",
			Handler:    _PlayerService_GetShuffle_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PlayerService_GetStatus_Handler,
		},
		{
			MethodName: "GetCurrentTrack",
			Handler:    _PlayerService_GetCurrentTrack_Handler,
		},
		{
			MethodName: "GetCDDevices",
			Handler:    _PlayerService_GetCDDevices_Handler,
		},
		{
			MethodName: "ReadCD",
			Handler:    _PlayerService_ReadCD_Handler,
		},
		{
			MethodName: "LoadCD",
			Handler:    _PlayerService_LoadCD_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _PlayerService_ListProviders_Handler,
		},
		{
			MethodName: "SearchTracks",
			Handler:    _PlayerService_SearchTracks_Handler,
		},
		{
			MethodName: "SearchPlaylists",
			Handler:    _PlayerService_SearchPlaylists_Handler,
		},
		{
			MethodName: "GetProviderTrackDetails",
			Handler:    _PlayerService_GetProviderTrackDetails_Handler,
		},
		{
			MethodName: "ResolveProviderStream",
			Handler:    _PlayerService_ResolveProviderStream_Handler,
		},
		{
			MethodName: "GetProviderPlaylistDetails",
			Handler:    _PlayerService_GetProviderPlaylistDetails_Handler,
		},
		{
			MethodName: "AddProviderTrack",
			Handler:    _PlayerService_AddProviderTrack_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeEvents",
			Handler:       _PlayerService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/player/v1/player.proto",
}
