// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/player/v1/player.proto

package playerv1

import (
	v1 "github.com/gg582/gozik/api/music/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlaybackState int32

const (
	PlaybackState_PLAYBACK_STATE_UNSPECIFIED PlaybackState = 0
	PlaybackState_PLAYBACK_STATE_STOPPED     PlaybackState = 1
	PlaybackState_PLAYBACK_STATE_PLAYING     PlaybackState = 2
	PlaybackState_PLAYBACK_STATE_PAUSED      PlaybackState = 3
)

// Enum value maps for PlaybackState.
var (
	PlaybackState_name = map[int32]string{
		0: "PLAYBACK_STATE_UNSPECIFIED",
		1: "PLAYBACK_STATE_STOPPED",
		2: "PLAYBACK_STATE_PLAYING",
		3: "PLAYBACK_STATE_PAUSED",
	}
	PlaybackState_value = map[string]int32{
		"PLAYBACK_STATE_UNSPECIFIED": 0,
		"PLAYBACK_STATE_STOPPED":     1,
		"PLAYBACK_STATE_PLAYING":     2,
		"PLAYBACK_STATE_PAUSED":      3,
	}
)

func (x PlaybackState) Enum() *PlaybackState {
	p := new(PlaybackState)
	*p = x
	return p
}

func (x PlaybackState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlaybackState) Descriptor() protoreflect.EnumDescriptor {
	return file_api_player_v1_player_proto_enumTypes[0].Descriptor()
}

func (PlaybackState) Type() protoreflect.EnumType {
	return &file_api_player_v1_player_proto_enumTypes[0]
}

func (x PlaybackState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlaybackState.Descriptor instead.
func (PlaybackState) EnumDescriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{0}
}

type RepeatMode int32

const (
	RepeatMode_REPEAT_MODE_UNSPECIFIED RepeatMode = 0
	RepeatMode_REPEAT_MODE_SEQUENTIAL  RepeatMode = 1
	RepeatMode_REPEAT_MODE_REPEAT_ALL  RepeatMode = 2
	RepeatMode_REPEAT_MODE_REPEAT_ONE  RepeatMode = 3
)

// Enum value maps for RepeatMode.
var (
	RepeatMode_name = map[int32]string{
		0: "REPEAT_MODE_UNSPECIFIED",
		1: "REPEAT_MODE_SEQUENTIAL",
		2: "REPEAT_MODE_REPEAT_ALL",
		3: "REPEAT_MODE_REPEAT_ONE",
	}
	RepeatMode_value = map[string]int32{
		"REPEAT_MODE_UNSPECIFIED": 0,
		"REPEAT_MODE_SEQUENTIAL":  1,
		"REPEAT_MODE_REPEAT_ALL":  2,
		"REPEAT_MODE_REPEAT_ONE":  3,
	}
)

func (x RepeatMode) Enum() *RepeatMode {
	p := new(RepeatMode)
	*p = x
	return p
}

func (x RepeatMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RepeatMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_player_v1_player_proto_enumTypes[1].Descriptor()
}

func (RepeatMode) Type() protoreflect.EnumType {
	return &file_api_player_v1_player_proto_enumTypes[1]
}

func (x RepeatMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RepeatMode.Descriptor instead.
func (RepeatMode) EnumDescriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{1}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED            EventType = 0
	EventType_EVENT_TYPE_PLAYBACK_STATE_CHANGED EventType = 1
	EventType_EVENT_TYPE_TRACK_CHANGED          EventType = 2
	EventType_EVENT_TYPE_POSITION_CHANGED       EventType = 3
	EventType_EVENT_TYPE_QUEUE_CHANGED          EventType = 4
	EventType_EVENT_TYPE_VOLUME_CHANGED         EventType = 5
	EventType_EVENT_TYPE_REPEAT_MODE_CHANGED    EventType = 6
	EventType_EVENT_TYPE_SHUFFLE_CHANGED        EventType = 7
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_PLAYBACK_STATE_CHANGED",
		2: "EVENT_TYPE_TRACK_CHANGED",
		3: "EVENT_TYPE_POSITION_CHANGED",
		4: "EVENT_TYPE_QUEUE_CHANGED",
		5: "EVENT_TYPE_VOLUME_CHANGED",
		6: "EVENT_TYPE_REPEAT_MODE_CHANGED",
		7: "EVENT_TYPE_SHUFFLE_CHANGED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":            0,
		"EVENT_TYPE_PLAYBACK_STATE_CHANGED": 1,
		"EVENT_TYPE_TRACK_CHANGED":          2,
		"EVENT_TYPE_POSITION_CHANGED":       3,
		"EVENT_TYPE_QUEUE_CHANGED":          4,
		"EVENT_TYPE_VOLUME_CHANGED":         5,
		"EVENT_TYPE_REPEAT_MODE_CHANGED":    6,
		"EVENT_TYPE_SHUFFLE_CHANGED":        7,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_player_v1_player_proto_enumTypes[2].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_api_player_v1_player_proto_enumTypes[2]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{2}
}

type Track struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Index           int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location        string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	Device          string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	TrackNum        int32                  `protobuf:"varint,5,opt,name=track_num,json=trackNum,proto3" json:"track_num,omitempty"`
	IsCd            bool                   `protobuf:"varint,6,opt,name=is_cd,json=isCd,proto3" json:"is_cd,omitempty"`
	Artist          string                 `protobuf:"bytes,7,opt,name=artist,proto3" json:"artist,omitempty"`
	Title           string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Album           string                 `protobuf:"bytes,9,opt,name=album,proto3" json:"album,omitempty"`
	AlbumYear       string                 `protobuf:"bytes,10,opt,name=album_year,json=albumYear,proto3" json:"album_year,omitempty"`
	DurationSeconds int32                  `protobuf:"varint,11,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	CoverArtUrl     string                 `protobuf:"bytes,12,opt,name=cover_art_url,json=coverArtUrl,proto3" json:"cover_art_url,omitempty"`
	StartOffset     int32                  `protobuf:"varint,13,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset       int32                  `protobuf:"varint,14,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	ProviderId      string                 `protobuf:"bytes,15,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderName    string                 `protobuf:"bytes,16,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderTrackId string                 `protobuf:"bytes,17,opt,name=provider_track_id,json=providerTrackId,proto3" json:"provider_track_id,omitempty"`
	StreamUrl       string                 `protobuf:"bytes,18,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_api_player_v1_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{0}
}

func (x *Track) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Track) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Track) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Track) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Track) GetTrackNum() int32 {
	if x != nil {
		return x.TrackNum
	}
	return 0
}

func (x *Track) GetIsCd() bool {
	if x != nil {
		return x.IsCd
	}
	return false
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Track) GetAlbumYear() string {
	if x != nil {
		return x.AlbumYear
	}
	return ""
}

func (x *Track) GetDurationSeconds() int32 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Track) GetCoverArtUrl() string {
	if x != nil {
		return x.CoverArtUrl
	}
	return ""
}

func (x *Track) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *Track) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *Track) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *Track) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *Track) GetProviderTrackId() string {
	if x != nil {
		return x.ProviderTrackId
	}
	return ""
}

func (x *Track) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

type Queue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	CurrentIndex  int32                  `protobuf:"varint,2,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_api_player_v1_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{1}
}

func (x *Queue) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *Queue) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaybackState PlaybackState          `protobuf:"varint,1,opt,name=playback_state,json=playbackState,proto3,enum=player.v1.PlaybackState" json:"playback_state,omitempty"`
	CurrentIndex  int32                  `protobuf:"varint,2,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	PositionMs    int64                  `protobuf:"varint,3,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	LengthMs      int64                  `protobuf:"varint,4,opt,name=length_ms,json=lengthMs,proto3" json:"length_ms,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Muted         bool                   `protobuf:"varint,6,opt,name=muted,proto3" json:"muted,omitempty"`
	RepeatMode    RepeatMode             `protobuf:"varint,7,opt,name=repeat_mode,json=repeatMode,proto3,enum=player.v1.RepeatMode" json:"repeat_mode,omitempty"`
	Shuffle       bool                   `protobuf:"varint,8,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_player_v1_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetPlaybackState() PlaybackState {
	if x != nil {
		return x.PlaybackState
	}
	return PlaybackState_PLAYBACK_STATE_UNSPECIFIED
}

func (x *Status) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

func (x *Status) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

func (x *Status) GetLengthMs() int64 {
	if x != nil {
		return x.LengthMs
	}
	return 0
}

func (x *Status) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Status) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *Status) GetRepeatMode() RepeatMode {
	if x != nil {
		return x.RepeatMode
	}
	return RepeatMode_REPEAT_MODE_UNSPECIFIED
}

func (x *Status) GetShuffle() bool {
	if x != nil {
		return x.Shuffle
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_player_v1_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{3}
}

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        float64                `protobuf:"fixed64,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_api_player_v1_player_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{4}
}

func (x *Volume) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PositionMs    int64                  `protobuf:"varint,1,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_api_player_v1_player_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{5}
}

func (x *Position) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

type Mute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Muted         bool                   `protobuf:"varint,1,opt,name=muted,proto3" json:"muted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mute) Reset() {
	*x = Mute{}
	mi := &file_api_player_v1_player_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mute) ProtoMessage() {}

func (x *Mute) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mute.ProtoReflect.Descriptor instead.
func (*Mute) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{6}
}

func (x *Mute) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type PlayIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayIndexRequest) Reset() {
	*x = PlayIndexRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayIndexRequest) ProtoMessage() {}

func (x *PlayIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayIndexRequest.ProtoReflect.Descriptor instead.
func (*PlayIndexRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{7}
}

func (x *PlayIndexRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indices       []int32                `protobuf:"varint,1,rep,packed,name=indices,proto3" json:"indices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveRequest) GetIndices() []int32 {
	if x != nil {
		return x.Indices
	}
	return nil
}

type QueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{9}
}

func (x *QueueRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type PlaylistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaylistRequest) Reset() {
	*x = PlaylistRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaylistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaylistRequest) ProtoMessage() {}

func (x *PlaylistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaylistRequest.ProtoReflect.Descriptor instead.
func (*PlaylistRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{10}
}

func (x *PlaylistRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RepeatModeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          RepeatMode             `protobuf:"varint,1,opt,name=mode,proto3,enum=player.v1.RepeatMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepeatModeRequest) Reset() {
	*x = RepeatModeRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepeatModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepeatModeRequest) ProtoMessage() {}

func (x *RepeatModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepeatModeRequest.ProtoReflect.Descriptor instead.
func (*RepeatModeRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{11}
}

func (x *RepeatModeRequest) GetMode() RepeatMode {
	if x != nil {
		return x.Mode
	}
	return RepeatMode_REPEAT_MODE_UNSPECIFIED
}

type ShuffleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShuffleRequest) Reset() {
	*x = ShuffleRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShuffleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShuffleRequest) ProtoMessage() {}

func (x *ShuffleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShuffleRequest.ProtoReflect.Descriptor instead.
func (*ShuffleRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{12}
}

func (x *ShuffleRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{13}
}

type PlayerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=player.v1.EventType" json:"type,omitempty"`
	Status        *Status                `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Track         *Track                 `protobuf:"bytes,3,opt,name=track,proto3" json:"track,omitempty"`
	PositionMs    int64                  `protobuf:"varint,4,opt,name=position_ms,json=positionMs,proto3" json:"position_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEvent) Reset() {
	*x = PlayerEvent{}
	mi := &file_api_player_v1_player_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEvent) ProtoMessage() {}

func (x *PlayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEvent.ProtoReflect.Descriptor instead.
func (*PlayerEvent) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *PlayerEvent) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *PlayerEvent) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *PlayerEvent) GetPositionMs() int64 {
	if x != nil {
		return x.PositionMs
	}
	return 0
}

type CDDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Supported     bool                   `protobuf:"varint,2,opt,name=supported,proto3" json:"supported,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDDevice) Reset() {
	*x = CDDevice{}
	mi := &file_api_player_v1_player_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDDevice) ProtoMessage() {}

func (x *CDDevice) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDDevice.ProtoReflect.Descriptor instead.
func (*CDDevice) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{15}
}

func (x *CDDevice) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CDDevice) GetSupported() bool {
	if x != nil {
		return x.Supported
	}
	return false
}

type CDTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	StartLba      int32                  `protobuf:"varint,2,opt,name=start_lba,json=startLba,proto3" json:"start_lba,omitempty"`
	EndLba        int32                  `protobuf:"varint,3,opt,name=end_lba,json=endLba,proto3" json:"end_lba,omitempty"`
	LengthFrames  int32                  `protobuf:"varint,4,opt,name=length_frames,json=lengthFrames,proto3" json:"length_frames,omitempty"`
	IsAudio       bool                   `protobuf:"varint,5,opt,name=is_audio,json=isAudio,proto3" json:"is_audio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CDTrack) Reset() {
	*x = CDTrack{}
	mi := &file_api_player_v1_player_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CDTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDTrack) ProtoMessage() {}

func (x *CDTrack) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDTrack.ProtoReflect.Descriptor instead.
func (*CDTrack) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{16}
}

func (x *CDTrack) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *CDTrack) GetStartLba() int32 {
	if x != nil {
		return x.StartLba
	}
	return 0
}

func (x *CDTrack) GetEndLba() int32 {
	if x != nil {
		return x.EndLba
	}
	return 0
}

func (x *CDTrack) GetLengthFrames() int32 {
	if x != nil {
		return x.LengthFrames
	}
	return 0
}

func (x *CDTrack) GetIsAudio() bool {
	if x != nil {
		return x.IsAudio
	}
	return false
}

type GetCDDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCDDevicesRequest) Reset() {
	*x = GetCDDevicesRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCDDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCDDevicesRequest) ProtoMessage() {}

func (x *GetCDDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCDDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetCDDevicesRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{17}
}

type GetCDDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*CDDevice            `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCDDevicesResponse) Reset() {
	*x = GetCDDevicesResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCDDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCDDevicesResponse) ProtoMessage() {}

func (x *GetCDDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCDDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetCDDevicesResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{18}
}

func (x *GetCDDevicesResponse) GetDevices() []*CDDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type ReadCDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCDRequest) Reset() {
	*x = ReadCDRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCDRequest) ProtoMessage() {}

func (x *ReadCDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCDRequest.ProtoReflect.Descriptor instead.
func (*ReadCDRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{19}
}

func (x *ReadCDRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ReadCDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Tracks        []*CDTrack             `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadCDResponse) Reset() {
	*x = ReadCDResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadCDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadCDResponse) ProtoMessage() {}

func (x *ReadCDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadCDResponse.ProtoReflect.Descriptor instead.
func (*ReadCDResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{20}
}

func (x *ReadCDResponse) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *ReadCDResponse) GetTracks() []*CDTrack {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type LoadCDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCDRequest) Reset() {
	*x = LoadCDRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCDRequest) ProtoMessage() {}

func (x *LoadCDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCDRequest.ProtoReflect.Descriptor instead.
func (*LoadCDRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{21}
}

func (x *LoadCDRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_api_player_v1_player_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{22}
}

func (x *ProviderInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ListProvidersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersRequest) Reset() {
	*x = ListProvidersRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersRequest) ProtoMessage() {}

func (x *ListProvidersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersRequest.ProtoReflect.Descriptor instead.
func (*ListProvidersRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{23}
}

type ListProvidersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Providers     []*ProviderInfo        `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProvidersResponse) Reset() {
	*x = ListProvidersResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProvidersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProvidersResponse) ProtoMessage() {}

func (x *ListProvidersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProvidersResponse.ProtoReflect.Descriptor instead.
func (*ListProvidersResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{24}
}

func (x *ListProvidersResponse) GetProviders() []*ProviderInfo {
	if x != nil {
		return x.Providers
	}
	return nil
}

type SearchTracksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracksRequest) Reset() {
	*x = SearchTracksRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracksRequest) ProtoMessage() {}

func (x *SearchTracksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracksRequest.ProtoReflect.Descriptor instead.
func (*SearchTracksRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{25}
}

func (x *SearchTracksRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SearchTracksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTracksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchTracksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*v1.Track            `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTracksResponse) Reset() {
	*x = SearchTracksResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTracksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTracksResponse) ProtoMessage() {}

func (x *SearchTracksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTracksResponse.ProtoReflect.Descriptor instead.
func (*SearchTracksResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{26}
}

func (x *SearchTracksResponse) GetTracks() []*v1.Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type SearchPlaylistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlaylistsRequest) Reset() {
	*x = SearchPlaylistsRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlaylistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlaylistsRequest) ProtoMessage() {}

func (x *SearchPlaylistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlaylistsRequest.ProtoReflect.Descriptor instead.
func (*SearchPlaylistsRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{27}
}

func (x *SearchPlaylistsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *SearchPlaylistsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchPlaylistsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchPlaylistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*v1.Playlist         `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchPlaylistsResponse) Reset() {
	*x = SearchPlaylistsResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchPlaylistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchPlaylistsResponse) ProtoMessage() {}

func (x *SearchPlaylistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchPlaylistsResponse.ProtoReflect.Descriptor instead.
func (*SearchPlaylistsResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{28}
}

func (x *SearchPlaylistsResponse) GetPlaylists() []*v1.Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

type ProviderTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderTrackRequest) Reset() {
	*x = ProviderTrackRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderTrackRequest) ProtoMessage() {}

func (x *ProviderTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderTrackRequest.ProtoReflect.Descriptor instead.
func (*ProviderTrackRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{29}
}

func (x *ProviderTrackRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *ProviderTrackRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type GetProviderTrackDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *v1.Track              `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderTrackDetailsResponse) Reset() {
	*x = GetProviderTrackDetailsResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderTrackDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderTrackDetailsResponse) ProtoMessage() {}

func (x *GetProviderTrackDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderTrackDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetProviderTrackDetailsResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{30}
}

func (x *GetProviderTrackDetailsResponse) GetTrack() *v1.Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type ResolveProviderStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveProviderStreamResponse) Reset() {
	*x = ResolveProviderStreamResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveProviderStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveProviderStreamResponse) ProtoMessage() {}

func (x *ResolveProviderStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveProviderStreamResponse.ProtoReflect.Descriptor instead.
func (*ResolveProviderStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{31}
}

func (x *ResolveProviderStreamResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *ResolveProviderStreamResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type GetProviderPlaylistDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	PlaylistId    string                 `protobuf:"bytes,2,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderPlaylistDetailsRequest) Reset() {
	*x = GetProviderPlaylistDetailsRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderPlaylistDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderPlaylistDetailsRequest) ProtoMessage() {}

func (x *GetProviderPlaylistDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderPlaylistDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetProviderPlaylistDetailsRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{32}
}

func (x *GetProviderPlaylistDetailsRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetProviderPlaylistDetailsRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetProviderPlaylistDetailsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetProviderPlaylistDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *v1.Playlist           `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	Tracks        []*v1.Track            `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderPlaylistDetailsResponse) Reset() {
	*x = GetProviderPlaylistDetailsResponse{}
	mi := &file_api_player_v1_player_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderPlaylistDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderPlaylistDetailsResponse) ProtoMessage() {}

func (x *GetProviderPlaylistDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderPlaylistDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetProviderPlaylistDetailsResponse) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{33}
}

func (x *GetProviderPlaylistDetailsResponse) GetPlaylist() *v1.Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

func (x *GetProviderPlaylistDetailsResponse) GetTracks() []*v1.Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type AddProviderTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	TrackId       string                 `protobuf:"bytes,2,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderTrackRequest) Reset() {
	*x = AddProviderTrackRequest{}
	mi := &file_api_player_v1_player_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderTrackRequest) ProtoMessage() {}

func (x *AddProviderTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_player_v1_player_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderTrackRequest.ProtoReflect.Descriptor instead.
func (*AddProviderTrackRequest) Descriptor() ([]byte, []int) {
	return file_api_player_v1_player_proto_rawDescGZIP(), []int{34}
}

func (x *AddProviderTrackRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *AddProviderTrackRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

var File_api_player_v1_player_proto protoreflect.FileDescriptor

const file_api_player_v1_player_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/player/v1/player.proto\x12\tplayer.v1\x1a!api/music/v1/music_provider.proto\"\x9c\x04\n" +
	"\x05Track\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x1b\n" +
	"\ttrack_num\x18\x05 \x01(\x05R\btrackNum\x12\x13\n" +
	"\x05is_cd\x18\x06 \x01(\bR\x04isCd\x12\x16\n" +
	"\x06artist\x18\a \x01(\tR\x06artist\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x14\n" +
	"\x05album\x18\t \x01(\tR\x05album\x12\x1d\n" +
	"\n" +
	"album_year\x18\n" +
	" \x01(\tR\talbumYear\x12)\n" +
	"\x10duration_seconds\x18\v \x01(\x05R\x0fdurationSeconds\x12\"\n" +
	"\rcover_art_url\x18\f \x01(\tR\vcoverArtUrl\x12!\n" +
	"\fstart_offset\x18\r \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x0e \x01(\x05R\tendOffset\x12\x1f\n" +
	"\vprovider_id\x18\x0f \x01(\tR\n" +
	"providerId\x12#\n" +
	"\rprovider_name\x18\x10 \x01(\tR\fproviderName\x12*\n" +
	"\x11provider_track_id\x18\x11 \x01(\tR\x0fproviderTrackId\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x12 \x01(\tR\tstreamUrl\"V\n" +
	"\x05Queue\x12(\n" +
	"\x06tracks\x18\x01 \x03(\v2\x10.player.v1.TrackR\x06tracks\x12#\n" +
	"\rcurrent_index\x18\x02 \x01(\x05R\fcurrentIndex\"\xac\x02\n" +
	"\x06Status\x12?\n" +
	"\x0eplayback_state\x18\x01 \x01(\x0e2\x18.player.v1.PlaybackStateR\rplaybackState\x12#\n" +
	"\rcurrent_index\x18\x02 \x01(\x05R\fcurrentIndex\x12\x1f\n" +
	"\vposition_ms\x18\x03 \x01(\x03R\n" +
	"positionMs\x12\x1b\n" +
	"\tlength_ms\x18\x04 \x01(\x03R\blengthMs\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x01R\x06volume\x12\x14\n" +
	"\x05muted\x18\x06 \x01(\bR\x05muted\x126\n" +
	"\vrepeat_mode\x18\a \x01(\x0e2\x15.player.v1.RepeatModeR\n" +
	"repeatMode\x12\x18\n" +
	"\ashuffle\x18\b \x01(\bR\ashuffle\"\a\n" +
	"\x05Empty\" \n" +
	"\x06Volume\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\x01R\x06volume\"+\n" +
	"\bPosition\x12\x1f\n" +
	"\vposition_ms\x18\x01 \x01(\x03R\n" +
	"positionMs\"\x1c\n" +
	"\x04Mute\x12\x14\n" +
	"\x05muted\x18\x01 \x01(\bR\x05muted\"(\n" +
	"\x10PlayIndexRequest\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\")\n" +
	"\rRemoveRequest\x12\x18\n" +
	"\aindices\x18\x01 \x03(\x05R\aindices\"$\n" +
	"\fQueueRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"%\n" +
	"\x0fPlaylistRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\">\n" +
	"\x11RepeatModeRequest\x12)\n" +
	"\x04mode\x18\x01 \x01(\x0e2\x15.player.v1.RepeatModeR\x04mode\"*\n" +
	"\x0eShuffleRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\"\x12\n" +
	"\x10SubscribeRequest\"\xab\x01\n" +
	"\vPlayerEvent\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.player.v1.EventTypeR\x04type\x12)\n" +
	"\x06status\x18\x02 \x01(\v2\x11.player.v1.StatusR\x06status\x12&\n" +
	"\x05track\x18\x03 \x01(\v2\x10.player.v1.TrackR\x05track\x12\x1f\n" +
	"\vposition_ms\x18\x04 \x01(\x03R\n" +
	"positionMs\"@\n" +
	"\bCDDevice\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1c\n" +
	"\tsupported\x18\x02 \x01(\bR\tsupported\"\x97\x01\n" +
	"\aCDTrack\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x1b\n" +
	"\tstart_lba\x18\x02 \x01(\x05R\bstartLba\x12\x17\n" +
	"\aend_lba\x18\x03 \x01(\x05R\x06endLba\x12#\n" +
	"\rlength_frames\x18\x04 \x01(\x05R\flengthFrames\x12\x19\n" +
	"\bis_audio\x18\x05 \x01(\bR\aisAudio\"\x15\n" +
	"\x13GetCDDevicesRequest\"E\n" +
	"\x14GetCDDevicesResponse\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.player.v1.CDDeviceR\adevices\"'\n" +
	"\rReadCDRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"T\n" +
	"\x0eReadCDResponse\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12*\n" +
	"\x06tracks\x18\x02 \x03(\v2\x12.player.v1.CDTrackR\x06tracks\"'\n" +
	"\rLoadCDRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"L\n" +
	"\fProviderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\x16\n" +
	"\x14ListProvidersRequest\"N\n" +
	"\x15ListProvidersResponse\x125\n" +
	"\tproviders\x18\x01 \x03(\v2\x17.player.v1.ProviderInfoR\tproviders\"b\n" +
	"\x13SearchTracksRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"?\n" +
	"\x14SearchTracksResponse\x12'\n" +
	"\x06tracks\x18\x01 \x03(\v2\x0f.music.v1.TrackR\x06tracks\"e\n" +
	"\x16SearchPlaylistsRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x17SearchPlaylistsResponse\x120\n" +
	"\tplaylists\x18\x01 \x03(\v2\x12.music.v1.PlaylistR\tplaylists\"R\n" +
	"\x14ProviderTrackRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId\"H\n" +
	"\x1fGetProviderTrackDetailsResponse\x12%\n" +
	"\x05track\x18\x01 \x01(\v2\x0f.music.v1.TrackR\x05track\"\xcb\x01\n" +
	"\x1dResolveProviderStreamResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12O\n" +
	"\aheaders\x18\x02 \x03(\v25.player.v1.ResolveProviderStreamResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"!GetProviderPlaylistDetailsRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x1f\n" +
	"\vplaylist_id\x18\x02 \x01(\tR\n" +
	"playlistId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"}\n" +
	"\"GetProviderPlaylistDetailsResponse\x12.\n" +
	"\bplaylist\x18\x01 \x01(\v2\x12.music.v1.PlaylistR\bplaylist\x12'\n" +
	"\x06tracks\x18\x02 \x03(\v2\x0f.music.v1.TrackR\x06tracks\"U\n" +
	"\x17AddProviderTrackRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12\x19\n" +
	"\btrack_id\x18\x02 \x01(\tR\atrackId*\x82\x01\n" +
	"\rPlaybackState\x12\x1e\n" +
	"\x1aPLAYBACK_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PLAYBACK_STATE_STOPPED\x10\x01\x12\x1a\n" +
	"\x16PLAYBACK_STATE_PLAYING\x10\x02\x12\x19\n" +
	"\x15PLAYBACK_STATE_PAUSED\x10\x03*}\n" +
	"\n" +
	"RepeatMode\x12\x1b\n" +
	"\x17REPEAT_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16REPEAT_MODE_SEQUENTIAL\x10\x01\x12\x1a\n" +
	"\x16REPEAT_MODE_REPEAT_ALL\x10\x02\x12\x1a\n" +
	"\x16REPEAT_MODE_REPEAT_ONE\x10\x03*\x8e\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!EVENT_TYPE_PLAYBACK_STATE_CHANGED\x10\x01\x12\x1c\n" +
	"\x18EVENT_TYPE_TRACK_CHANGED\x10\x02\x12\x1f\n" +
	"\x1bEVENT_TYPE_POSITION_CHANGED\x10\x03\x12\x1c\n" +
	"\x18EVENT_TYPE_QUEUE_CHANGED\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_VOLUME_CHANGED\x10\x05\x12\"\n" +
	"\x1eEVENT_TYPE_REPEAT_MODE_CHANGED\x10\x06\x12\x1e\n" +
	"\x1aEVENT_TYPE_SHUFFLE_CHANGED\x10\a2\xf2\x10\n" +
	"\rPlayerService\x12*\n" +
	"\x04Play\x12\x10.player.v1.Empty\x1a\x10.player.v1.Empty\x12+\n" +
	"\x05Pause\x12\x10.player.v1.Empty\x1a\x10.player.v1.Empty\x12*\n" +
	"\x04Stop\x12\x10.player.v1.Empty\x1a\x10.player.v1.Empty\x12*\n" +
	"\x04Next\x12\x10.player.v1.Empty\x1a\x10.player.v1.Empty\x12.\n" +
	"\bPrevious\x12\x10.player.v1.Empty\x1a\x10.player.v1.Empty\x12:\n" +
	"\tPlayIndex\x12\x1b.player.v1.PlayIndexRequest\x1a\x10.player.v1.Empty\x12-\n" +
	"\x04Seek\x12\x13.player.v1.Position\x1a\x10.player.v1.Empty\x120\n" +
	"\tSetVolume\x12\x11.player.v1.Volume\x1a\x10.player.v1.Empty\x120\n" +
	"\tGetVolume\x12\x10.player.v1.Empty\x1a\x11.player.v1.Volume\x12,\n" +
	"\aSetMute\x12\x0f.player.v1.Mute\x1a\x10.player.v1.Empty\x12,\n" +
	"\aGetMute\x12\x10.player.v1.Empty\x1a\x0f.player.v1.Mute\x12.\n" +
	"\bGetQueue\x12\x10.player.v1.Empty\x1a\x10.player.v1.Queue\x127\n" +
	"\n" +
	"AddToQueue\x12\x17.player.v1.QueueRequest\x1a\x10.player.v1.Empty\x12=\n" +
	"\x0fRemoveFromQueue\x12\x18.player.v1.RemoveRequest\x1a\x10.player.v1.Empty\x120\n" +
	"\n" +
	"ClearQueue\x12\x10.player.v1.Empty\x1a\x10.player.v1.Empty\x12<\n" +
	"\fLoadPlaylist\x12\x1a.player.v1.PlaylistRequest\x1a\x10.player.v1.Empty\x12<\n" +
	"\fSavePlaylist\x12\x1a.player.v1.PlaylistRequest\x1a\x10.player.v1.Empty\x12?\n" +
	"\rSetRepeatMode\x12\x1c.player.v1.RepeatModeRequest\x1a\x10.player.v1.Empty\x12?\n" +
	"\rGetRepeatMode\x12\x10.player.v1.Empty\x1a\x1c.player.v1.RepeatModeRequest\x129\n" +
	"\n" +
	"SetShuffle\x12\x19.player.v1.ShuffleRequest\x1a\x10.player.v1.Empty\x129\n" +
	"\n" +
	"GetShuffle\x12\x10.player.v1.Empty\x1a\x19.player.v1.ShuffleRequest\x120\n" +
	"\tGetStatus\x12\x10.player.v1.Empty\x1a\x11.player.v1.Status\x125\n" +
	"\x0fGetCurrentTrack\x12\x10.player.v1.Empty\x1a\x10.player.v1.Track\x12O\n" +
	"\fGetCDDevices\x12\x1e.player.v1.GetCDDevicesRequest\x1a\x1f.player.v1.GetCDDevicesResponse\x12=\n" +
	"\x06ReadCD\x12\x18.player.v1.ReadCDRequest\x1a\x19.player.v1.ReadCDResponse\x124\n" +
	"\x06LoadCD\x12\x18.player.v1.LoadCDRequest\x1a\x10.player.v1.Empty\x12R\n" +
	"\rListProviders\x12\x1f.player.v1.ListProvidersRequest\x1a .player.v1.ListProvidersResponse\x12O\n" +
	"\fSearchTracks\x12\x1e.player.v1.SearchTracksRequest\x1a\x1f.player.v1.SearchTracksResponse\x12X\n" +
	"\x0fSearchPlaylists\x12!.player.v1.SearchPlaylistsRequest\x1a\".player.v1.SearchPlaylistsResponse\x12f\n" +
	"\x17GetProviderTrackDetails\x12\x1f.player.v1.ProviderTrackRequest\x1a*.player.v1.GetProviderTrackDetailsResponse\x12b\n" +
	"\x15ResolveProviderStream\x12\x1f.player.v1.ProviderTrackRequest\x1a(.player.v1.ResolveProviderStreamResponse\x12y\n" +
	"\x1aGetProviderPlaylistDetails\x12,.player.v1.GetProviderPlaylistDetailsRequest\x1a-.player.v1.GetProviderPlaylistDetailsResponse\x12H\n" +
	"\x10AddProviderTrack\x12\".player.v1.AddProviderTrackRequest\x1a\x10.player.v1.Empty\x12H\n" +
	"\x0fSubscribeEvents\x12\x1b.player.v1.SubscribeRequest\x1a\x16.player.v1.PlayerEvent0\x01B/Z-github.com/gg582/gozik/api/player/v1;playerv1b\x06proto3"

var (
	file_api_player_v1_player_proto_rawDescOnce sync.Once
	file_api_player_v1_player_proto_rawDescData []byte
)

func file_api_player_v1_player_proto_rawDescGZIP() []byte {
	file_api_player_v1_player_proto_rawDescOnce.Do(func() {
		file_api_player_v1_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_player_v1_player_proto_rawDesc), len(file_api_player_v1_player_proto_rawDesc)))
	})
	return file_api_player_v1_player_proto_rawDescData
}

var file_api_player_v1_player_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_player_v1_player_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_api_player_v1_player_proto_goTypes = []any{
	(PlaybackState)(0),                         // 0: player.v1.PlaybackState
	(RepeatMode)(0),                            // 1: player.v1.RepeatMode
	(EventType)(0),                             // 2: player.v1.EventType
	(*Track)(nil),                              // 3: player.v1.Track
	(*Queue)(nil),                              // 4: player.v1.Queue
	(*Status)(nil),                             // 5: player.v1.Status
	(*Empty)(nil),                              // 6: player.v1.Empty
	(*Volume)(nil),                             // 7: player.v1.Volume
	(*Position)(nil),                           // 8: player.v1.Position
	(*Mute)(nil),                               // 9: player.v1.Mute
	(*PlayIndexRequest)(nil),                   // 10: player.v1.PlayIndexRequest
	(*RemoveRequest)(nil),                      // 11: player.v1.RemoveRequest
	(*QueueRequest)(nil),                       // 12: player.v1.QueueRequest
	(*PlaylistRequest)(nil),                    // 13: player.v1.PlaylistRequest
	(*RepeatModeRequest)(nil),                  // 14: player.v1.RepeatModeRequest
	(*ShuffleRequest)(nil),                     // 15: player.v1.ShuffleRequest
	(*SubscribeRequest)(nil),                   // 16: player.v1.SubscribeRequest
	(*PlayerEvent)(nil),                        // 17: player.v1.PlayerEvent
	(*CDDevice)(nil),                           // 18: player.v1.CDDevice
	(*CDTrack)(nil),                            // 19: player.v1.CDTrack
	(*GetCDDevicesRequest)(nil),                // 20: player.v1.GetCDDevicesRequest
	(*GetCDDevicesResponse)(nil),               // 21: player.v1.GetCDDevicesResponse
	(*ReadCDRequest)(nil),                      // 22: player.v1.ReadCDRequest
	(*ReadCDResponse)(nil),                     // 23: player.v1.ReadCDResponse
	(*LoadCDRequest)(nil),                      // 24: player.v1.LoadCDRequest
	(*ProviderInfo)(nil),                       // 25: player.v1.ProviderInfo
	(*ListProvidersRequest)(nil),               // 26: player.v1.ListProvidersRequest
	(*ListProvidersResponse)(nil),              // 27: player.v1.ListProvidersResponse
	(*SearchTracksRequest)(nil),                // 28: player.v1.SearchTracksRequest
	(*SearchTracksResponse)(nil),               // 29: player.v1.SearchTracksResponse
	(*SearchPlaylistsRequest)(nil),             // 30: player.v1.SearchPlaylistsRequest
	(*SearchPlaylistsResponse)(nil),            // 31: player.v1.SearchPlaylistsResponse
	(*ProviderTrackRequest)(nil),               // 32: player.v1.ProviderTrackRequest
	(*GetProviderTrackDetailsResponse)(nil),    // 33: player.v1.GetProviderTrackDetailsResponse
	(*ResolveProviderStreamResponse)(nil),      // 34: player.v1.ResolveProviderStreamResponse
	(*GetProviderPlaylistDetailsRequest)(nil),  // 35: player.v1.GetProviderPlaylistDetailsRequest
	(*GetProviderPlaylistDetailsResponse)(nil), // 36: player.v1.GetProviderPlaylistDetailsResponse
	(*AddProviderTrackRequest)(nil),            // 37: player.v1.AddProviderTrackRequest
	nil,                                        // 38: player.v1.ResolveProviderStreamResponse.HeadersEntry
	(*v1.Track)(nil),                           // 39: music.v1.Track
	(*v1.Playlist)(nil),                        // 40: music.v1.Playlist
}
var file_api_player_v1_player_proto_depIdxs = []int32{
	3,  // 0: player.v1.Queue.tracks:type_name -> player.v1.Track
	0,  // 1: player.v1.Status.playback_state:type_name -> player.v1.PlaybackState
	1,  // 2: player.v1.Status.repeat_mode:type_name -> player.v1.RepeatMode
	1,  // 3: player.v1.RepeatModeRequest.mode:type_name -> player.v1.RepeatMode
	2,  // 4: player.v1.PlayerEvent.type:type_name -> player.v1.EventType
	5,  // 5: player.v1.PlayerEvent.status:type_name -> player.v1.Status
	3,  // 6: player.v1.PlayerEvent.track:type_name -> player.v1.Track
	18, // 7: player.v1.GetCDDevicesResponse.devices:type_name -> player.v1.CDDevice
	19, // 8: player.v1.ReadCDResponse.tracks:type_name -> player.v1.CDTrack
	25, // 9: player.v1.ListProvidersResponse.providers:type_name -> player.v1.ProviderInfo
	39, // 10: player.v1.SearchTracksResponse.tracks:type_name -> music.v1.Track
	40, // 11: player.v1.SearchPlaylistsResponse.playlists:type_name -> music.v1.Playlist
	39, // 12: player.v1.GetProviderTrackDetailsResponse.track:type_name -> music.v1.Track
	38, // 13: player.v1.ResolveProviderStreamResponse.headers:type_name -> player.v1.ResolveProviderStreamResponse.HeadersEntry
	40, // 14: player.v1.GetProviderPlaylistDetailsResponse.playlist:type_name -> music.v1.Playlist
	39, // 15: player.v1.GetProviderPlaylistDetailsResponse.tracks:type_name -> music.v1.Track
	6,  // 16: player.v1.PlayerService.Play:input_type -> player.v1.Empty
	6,  // 17: player.v1.PlayerService.Pause:input_type -> player.v1.Empty
	6,  // 18: player.v1.PlayerService.Stop:input_type -> player.v1.Empty
	6,  // 19: player.v1.PlayerService.Next:input_type -> player.v1.Empty
	6,  // 20: player.v1.PlayerService.Previous:input_type -> player.v1.Empty
	10, // 21: player.v1.PlayerService.PlayIndex:input_type -> player.v1.PlayIndexRequest
	8,  // 22: player.v1.PlayerService.Seek:input_type -> player.v1.Position
	7,  // 23: player.v1.PlayerService.SetVolume:input_type -> player.v1.Volume
	6,  // 24: player.v1.PlayerService.GetVolume:input_type -> player.v1.Empty
	9,  // 25: player.v1.PlayerService.SetMute:input_type -> player.v1.Mute
	6,  // 26: player.v1.PlayerService.GetMute:input_type -> player.v1.Empty
	6,  // 27: player.v1.PlayerService.GetQueue:input_type -> player.v1.Empty
	12, // 28: player.v1.PlayerService.AddToQueue:input_type -> player.v1.QueueRequest
	11, // 29: player.v1.PlayerService.RemoveFromQueue:input_type -> player.v1.RemoveRequest
	6,  // 30: player.v1.PlayerService.ClearQueue:input_type -> player.v1.Empty
	13, // 31: player.v1.PlayerService.LoadPlaylist:input_type -> player.v1.PlaylistRequest
	13, // 32: player.v1.PlayerService.SavePlaylist:input_type -> player.v1.PlaylistRequest
	14, // 33: player.v1.PlayerService.SetRepeatMode:input_type -> player.v1.RepeatModeRequest
	6,  // 34: player.v1.PlayerService.GetRepeatMode:input_type -> player.v1.Empty
	15, // 35: player.v1.PlayerService.SetShuffle:input_type -> player.v1.ShuffleRequest
	6,  // 36: player.v1.PlayerService.GetShuffle:input_type -> player.v1.Empty
	6,  // 37: player.v1.PlayerService.GetStatus:input_type -> player.v1.Empty
	6,  // 38: player.v1.PlayerService.GetCurrentTrack:input_type -> player.v1.Empty
	20, // 39: player.v1.PlayerService.GetCDDevices:input_type -> player.v1.GetCDDevicesRequest
	22, // 40: player.v1.PlayerService.ReadCD:input_type -> player.v1.ReadCDRequest
	24, // 41: player.v1.PlayerService.LoadCD:input_type -> player.v1.LoadCDRequest
	26, // 42: player.v1.PlayerService.ListProviders:input_type -> player.v1.ListProvidersRequest
	28, // 43: player.v1.PlayerService.SearchTracks:input_type -> player.v1.SearchTracksRequest
	30, // 44: player.v1.PlayerService.SearchPlaylists:input_type -> player.v1.SearchPlaylistsRequest
	32, // 45: player.v1.PlayerService.GetProviderTrackDetails:input_type -> player.v1.ProviderTrackRequest
	32, // 46: player.v1.PlayerService.ResolveProviderStream:input_type -> player.v1.ProviderTrackRequest
	35, // 47: player.v1.PlayerService.GetProviderPlaylistDetails:input_type -> player.v1.GetProviderPlaylistDetailsRequest
	37, // 48: player.v1.PlayerService.AddProviderTrack:input_type -> player.v1.AddProviderTrackRequest
	16, // 49: player.v1.PlayerService.SubscribeEvents:input_type -> player.v1.SubscribeRequest
	6,  // 50: player.v1.PlayerService.Play:output_type -> player.v1.Empty
	6,  // 51: player.v1.PlayerService.Pause:output_type -> player.v1.Empty
	6,  // 52: player.v1.PlayerService.Stop:output_type -> player.v1.Empty
	6,  // 53: player.v1.PlayerService.Next:output_type -> player.v1.Empty
	6,  // 54: player.v1.PlayerService.Previous:output_type -> player.v1.Empty
	6,  // 55: player.v1.PlayerService.PlayIndex:output_type -> player.v1.Empty
	6,  // 56: player.v1.PlayerService.Seek:output_type -> player.v1.Empty
	6,  // 57: player.v1.PlayerService.SetVolume:output_type -> player.v1.Empty
	7,  // 58: player.v1.PlayerService.GetVolume:output_type -> player.v1.Volume
	6,  // 59: player.v1.PlayerService.SetMute:output_type -> player.v1.Empty
	9,  // 60: player.v1.PlayerService.GetMute:output_type -> player.v1.Mute
	4,  // 61: player.v1.PlayerService.GetQueue:output_type -> player.v1.Queue
	6,  // 62: player.v1.PlayerService.AddToQueue:output_type -> player.v1.Empty
	6,  // 63: player.v1.PlayerService.RemoveFromQueue:output_type -> player.v1.Empty
	6,  // 64: player.v1.PlayerService.ClearQueue:output_type -> player.v1.Empty
	6,  // 65: player.v1.PlayerService.LoadPlaylist:output_type -> player.v1.Empty
	6,  // 66: player.v1.PlayerService.SavePlaylist:output_type -> player.v1.Empty
	6,  // 67: player.v1.PlayerService.SetRepeatMode:output_type -> player.v1.Empty
	14, // 68: player.v1.PlayerService.GetRepeatMode:output_type -> player.v1.RepeatModeRequest
	6,  // 69: player.v1.PlayerService.SetShuffle:output_type -> player.v1.Empty
	15, // 70: player.v1.PlayerService.GetShuffle:output_type -> player.v1.ShuffleRequest
	5,  // 71: player.v1.PlayerService.GetStatus:output_type -> player.v1.Status
	3,  // 72: player.v1.PlayerService.GetCurrentTrack:output_type -> player.v1.Track
	21, // 73: player.v1.PlayerService.GetCDDevices:output_type -> player.v1.GetCDDevicesResponse
	23, // 74: player.v1.PlayerService.ReadCD:output_type -> player.v1.ReadCDResponse
	6,  // 75: player.v1.PlayerService.LoadCD:output_type -> player.v1.Empty
	27, // 76: player.v1.PlayerService.ListProviders:output_type -> player.v1.ListProvidersResponse
	29, // 77: player.v1.PlayerService.SearchTracks:output_type -> player.v1.SearchTracksResponse
	31, // 78: player.v1.PlayerService.SearchPlaylists:output_type -> player.v1.SearchPlaylistsResponse
	33, // 79: player.v1.PlayerService.GetProviderTrackDetails:output_type -> player.v1.GetProviderTrackDetailsResponse
	34, // 80: player.v1.PlayerService.ResolveProviderStream:output_type -> player.v1.ResolveProviderStreamResponse
	36, // 81: player.v1.PlayerService.GetProviderPlaylistDetails:output_type -> player.v1.GetProviderPlaylistDetailsResponse
	6,  // 82: player.v1.PlayerService.AddProviderTrack:output_type -> player.v1.Empty
	17, // 83: player.v1.PlayerService.SubscribeEvents:output_type -> player.v1.PlayerEvent
	50, // [50:84] is the sub-list for method output_type
	16, // [16:50] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_player_v1_player_proto_init() }
func file_api_player_v1_player_proto_init() {
	if File_api_player_v1_player_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_player_v1_player_proto_rawDesc), len(file_api_player_v1_player_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_player_v1_player_proto_goTypes,
		DependencyIndexes: file_api_player_v1_player_proto_depIdxs,
		EnumInfos:         file_api_player_v1_player_proto_enumTypes,
		MessageInfos:      file_api_player_v1_player_proto_msgTypes,
	}.Build()
	File_api_player_v1_player_proto = out.File
	file_api_player_v1_player_proto_goTypes = nil
	file_api_player_v1_player_proto_depIdxs = nil
}
