// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/music/v1/music_provider.proto

package musicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MusicProviderService_GetProviderMetadata_FullMethodName = "/music.v1.MusicProviderService/GetProviderMetadata"
	MusicProviderService_InitiateAuth_FullMethodName        = "/music.v1.MusicProviderService/InitiateAuth"
	MusicProviderService_CompleteAuth_FullMethodName        = "/music.v1.MusicProviderService/CompleteAuth"
	MusicProviderService_RefreshAuth_FullMethodName         = "/music.v1.MusicProviderService/RefreshAuth"
	MusicProviderService_Search_FullMethodName              = "/music.v1.MusicProviderService/Search"
	MusicProviderService_SearchSuggestions_FullMethodName   = "/music.v1.MusicProviderService/SearchSuggestions"
	MusicProviderService_GetTrackDetails_FullMethodName     = "/music.v1.MusicProviderService/GetTrackDetails"
	MusicProviderService_ResolveStream_FullMethodName       = "/music.v1.MusicProviderService/ResolveStream"
	MusicProviderService_StreamAudio_FullMethodName         = "/music.v1.MusicProviderService/StreamAudio"
	MusicProviderService_GetUserLibrary_FullMethodName      = "/music.v1.MusicProviderService/GetUserLibrary"
	MusicProviderService_GetUserPlaylists_FullMethodName    = "/music.v1.MusicProviderService/GetUserPlaylists"
	MusicProviderService_GetPlaylistDetails_FullMethodName  = "/music.v1.MusicProviderService/GetPlaylistDetails"
)

// MusicProviderServiceClient is the client API for MusicProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MusicProviderServiceClient interface {
	GetProviderMetadata(ctx context.Context, in *GetProviderMetadataRequest, opts ...grpc.CallOption) (*GetProviderMetadataResponse, error)
	InitiateAuth(ctx context.Context, in *InitiateAuthRequest, opts ...grpc.CallOption) (*InitiateAuthResponse, error)
	CompleteAuth(ctx context.Context, in *CompleteAuthRequest, opts ...grpc.CallOption) (*CompleteAuthResponse, error)
	RefreshAuth(ctx context.Context, in *RefreshAuthRequest, opts ...grpc.CallOption) (*RefreshAuthResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	SearchSuggestions(ctx context.Context, in *SearchSuggestionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchSuggestionsResponse], error)
	GetTrackDetails(ctx context.Context, in *GetTrackDetailsRequest, opts ...grpc.CallOption) (*GetTrackDetailsResponse, error)
	ResolveStream(ctx context.Context, in *ResolveStreamRequest, opts ...grpc.CallOption) (*ResolveStreamResponse, error)
	StreamAudio(ctx context.Context, in *StreamAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error)
	GetUserLibrary(ctx context.Context, in *GetUserLibraryRequest, opts ...grpc.CallOption) (*GetUserLibraryResponse, error)
	GetUserPlaylists(ctx context.Context, in *GetUserPlaylistsRequest, opts ...grpc.CallOption) (*GetUserPlaylistsResponse, error)
	GetPlaylistDetails(ctx context.Context, in *GetPlaylistDetailsRequest, opts ...grpc.CallOption) (*GetPlaylistDetailsResponse, error)
}

type musicProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMusicProviderServiceClient(cc grpc.ClientConnInterface) MusicProviderServiceClient {
	return &musicProviderServiceClient{cc}
}

func (c *musicProviderServiceClient) GetProviderMetadata(ctx context.Context, in *GetProviderMetadataRequest, opts ...grpc.CallOption) (*GetProviderMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProviderMetadataResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_GetProviderMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) InitiateAuth(ctx context.Context, in *InitiateAuthRequest, opts ...grpc.CallOption) (*InitiateAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateAuthResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_InitiateAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) CompleteAuth(ctx context.Context, in *CompleteAuthRequest, opts ...grpc.CallOption) (*CompleteAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteAuthResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_CompleteAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) RefreshAuth(ctx context.Context, in *RefreshAuthRequest, opts ...grpc.CallOption) (*RefreshAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshAuthResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_RefreshAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) SearchSuggestions(ctx context.Context, in *SearchSuggestionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchSuggestionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MusicProviderService_ServiceDesc.Streams[0], MusicProviderService_SearchSuggestions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchSuggestionsRequest, SearchSuggestionsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MusicProviderService_SearchSuggestionsClient = grpc.ServerStreamingClient[SearchSuggestionsResponse]

func (c *musicProviderServiceClient) GetTrackDetails(ctx context.Context, in *GetTrackDetailsRequest, opts ...grpc.CallOption) (*GetTrackDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrackDetailsResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_GetTrackDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) ResolveStream(ctx context.Context, in *ResolveStreamRequest, opts ...grpc.CallOption) (*ResolveStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveStreamResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_ResolveStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) StreamAudio(ctx context.Context, in *StreamAudioRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AudioChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MusicProviderService_ServiceDesc.Streams[1], MusicProviderService_StreamAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamAudioRequest, AudioChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MusicProviderService_StreamAudioClient = grpc.ServerStreamingClient[AudioChunk]

func (c *musicProviderServiceClient) GetUserLibrary(ctx context.Context, in *GetUserLibraryRequest, opts ...grpc.CallOption) (*GetUserLibraryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLibraryResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_GetUserLibrary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) GetUserPlaylists(ctx context.Context, in *GetUserPlaylistsRequest, opts ...grpc.CallOption) (*GetUserPlaylistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserPlaylistsResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_GetUserPlaylists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *musicProviderServiceClient) GetPlaylistDetails(ctx context.Context, in *GetPlaylistDetailsRequest, opts ...grpc.CallOption) (*GetPlaylistDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlaylistDetailsResponse)
	err := c.cc.Invoke(ctx, MusicProviderService_GetPlaylistDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MusicProviderServiceServer is the server API for MusicProviderService service.
// All implementations must embed UnimplementedMusicProviderServiceServer
// for forward compatibility.
type MusicProviderServiceServer interface {
	GetProviderMetadata(context.Context, *GetProviderMetadataRequest) (*GetProviderMetadataResponse, error)
	InitiateAuth(context.Context, *InitiateAuthRequest) (*InitiateAuthResponse, error)
	CompleteAuth(context.Context, *CompleteAuthRequest) (*CompleteAuthResponse, error)
	RefreshAuth(context.Context, *RefreshAuthRequest) (*RefreshAuthResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	SearchSuggestions(*SearchSuggestionsRequest, grpc.ServerStreamingServer[SearchSuggestionsResponse]) error
	GetTrackDetails(context.Context, *GetTrackDetailsRequest) (*GetTrackDetailsResponse, error)
	ResolveStream(context.Context, *ResolveStreamRequest) (*ResolveStreamResponse, error)
	StreamAudio(*StreamAudioRequest, grpc.ServerStreamingServer[AudioChunk]) error
	GetUserLibrary(context.Context, *GetUserLibraryRequest) (*GetUserLibraryResponse, error)
	GetUserPlaylists(context.Context, *GetUserPlaylistsRequest) (*GetUserPlaylistsResponse, error)
	GetPlaylistDetails(context.Context, *GetPlaylistDetailsRequest) (*GetPlaylistDetailsResponse, error)
	mustEmbedUnimplementedMusicProviderServiceServer()
}

// UnimplementedMusicProviderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMusicProviderServiceServer struct{}

func (UnimplementedMusicProviderServiceServer) GetProviderMetadata(context.Context, *GetProviderMetadataRequest) (*GetProviderMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProviderMetadata not implemented")
}
func (UnimplementedMusicProviderServiceServer) InitiateAuth(context.Context, *InitiateAuthRequest) (*InitiateAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateAuth not implemented")
}
func (UnimplementedMusicProviderServiceServer) CompleteAuth(context.Context, *CompleteAuthRequest) (*CompleteAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteAuth not implemented")
}
func (UnimplementedMusicProviderServiceServer) RefreshAuth(context.Context, *RefreshAuthRequest) (*RefreshAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshAuth not implemented")
}
func (UnimplementedMusicProviderServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMusicProviderServiceServer) SearchSuggestions(*SearchSuggestionsRequest, grpc.ServerStreamingServer[SearchSuggestionsResponse]) error {
	return status.Error(codes.Unimplemented, "method SearchSuggestions not implemented")
}
func (UnimplementedMusicProviderServiceServer) GetTrackDetails(context.Context, *GetTrackDetailsRequest) (*GetTrackDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrackDetails not implemented")
}
func (UnimplementedMusicProviderServiceServer) ResolveStream(context.Context, *ResolveStreamRequest) (*ResolveStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveStream not implemented")
}
func (UnimplementedMusicProviderServiceServer) StreamAudio(*StreamAudioRequest, grpc.ServerStreamingServer[AudioChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamAudio not implemented")
}
func (UnimplementedMusicProviderServiceServer) GetUserLibrary(context.Context, *GetUserLibraryRequest) (*GetUserLibraryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserLibrary not implemented")
}
func (UnimplementedMusicProviderServiceServer) GetUserPlaylists(context.Context, *GetUserPlaylistsRequest) (*GetUserPlaylistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPlaylists not implemented")
}
func (UnimplementedMusicProviderServiceServer) GetPlaylistDetails(context.Context, *GetPlaylistDetailsRequest) (*GetPlaylistDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlaylistDetails not implemented")
}
func (UnimplementedMusicProviderServiceServer) mustEmbedUnimplementedMusicProviderServiceServer() {}
func (UnimplementedMusicProviderServiceServer) testEmbeddedByValue()                              {}

// UnsafeMusicProviderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MusicProviderServiceServer will
// result in compilation errors.
type UnsafeMusicProviderServiceServer interface {
	mustEmbedUnimplementedMusicProviderServiceServer()
}

func RegisterMusicProviderServiceServer(s grpc.ServiceRegistrar, srv MusicProviderServiceServer) {
	// If the following call panics, it indicates UnimplementedMusicProviderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MusicProviderService_ServiceDesc, srv)
}

func _MusicProviderService_GetProviderMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProviderMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).GetProviderMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_GetProviderMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).GetProviderMetadata(ctx, req.(*GetProviderMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_InitiateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).InitiateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_InitiateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).InitiateAuth(ctx, req.(*InitiateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_CompleteAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).CompleteAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_CompleteAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).CompleteAuth(ctx, req.(*CompleteAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_RefreshAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).RefreshAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_RefreshAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).RefreshAuth(ctx, req.(*RefreshAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_SearchSuggestions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchSuggestionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MusicProviderServiceServer).SearchSuggestions(m, &grpc.GenericServerStream[SearchSuggestionsRequest, SearchSuggestionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MusicProviderService_SearchSuggestionsServer = grpc.ServerStreamingServer[SearchSuggestionsResponse]

func _MusicProviderService_GetTrackDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrackDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).GetTrackDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_GetTrackDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).GetTrackDetails(ctx, req.(*GetTrackDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_ResolveStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).ResolveStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_ResolveStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).ResolveStream(ctx, req.(*ResolveStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamAudioRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MusicProviderServiceServer).StreamAudio(m, &grpc.GenericServerStream[StreamAudioRequest, AudioChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MusicProviderService_StreamAudioServer = grpc.ServerStreamingServer[AudioChunk]

func _MusicProviderService_GetUserLibrary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLibraryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).GetUserLibrary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_GetUserLibrary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).GetUserLibrary(ctx, req.(*GetUserLibraryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_GetUserPlaylists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPlaylistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).GetUserPlaylists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_GetUserPlaylists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).GetUserPlaylists(ctx, req.(*GetUserPlaylistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MusicProviderService_GetPlaylistDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlaylistDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MusicProviderServiceServer).GetPlaylistDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MusicProviderService_GetPlaylistDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MusicProviderServiceServer).GetPlaylistDetails(ctx, req.(*GetPlaylistDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MusicProviderService_ServiceDesc is the grpc.ServiceDesc for MusicProviderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MusicProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "music.v1.MusicProviderService",
	HandlerType: (*MusicProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProviderMetadata",
			Handler:    _MusicProviderService_GetProviderMetadata_Handler,
		},
		{
			MethodName: "InitiateAuth",
			Handler:    _MusicProviderService_InitiateAuth_Handler,
		},
		{
			MethodName: "CompleteAuth",
			Handler:    _MusicProviderService_CompleteAuth_Handler,
		},
		{
			MethodName: "RefreshAuth",
			Handler:    _MusicProviderService_RefreshAuth_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _MusicProviderService_Search_Handler,
		},
		{
			MethodName: "GetTrackDetails",
			Handler:    _MusicProviderService_GetTrackDetails_Handler,
		},
		{
			MethodName: "ResolveStream",
			Handler:    _MusicProviderService_ResolveStream_Handler,
		},
		{
			MethodName: "GetUserLibrary",
			Handler:    _MusicProviderService_GetUserLibrary_Handler,
		},
		{
			MethodName: "GetUserPlaylists",
			Handler:    _MusicProviderService_GetUserPlaylists_Handler,
		},
		{
			MethodName: "GetPlaylistDetails",
			Handler:    _MusicProviderService_GetPlaylistDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchSuggestions",
			Handler:       _MusicProviderService_SearchSuggestions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamAudio",
			Handler:       _MusicProviderService_StreamAudio_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/music/v1/music_provider.proto",
}
