// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: api/music/v1/music_provider.proto

package musicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProviderCapability int32

const (
	ProviderCapability_PROVIDER_CAPABILITY_UNSPECIFIED        ProviderCapability = 0
	ProviderCapability_PROVIDER_CAPABILITY_SEARCH             ProviderCapability = 1
	ProviderCapability_PROVIDER_CAPABILITY_STREAM_TRACK       ProviderCapability = 2
	ProviderCapability_PROVIDER_CAPABILITY_LIBRARY_MANAGEMENT ProviderCapability = 3
)

// Enum value maps for ProviderCapability.
var (
	ProviderCapability_name = map[int32]string{
		0: "PROVIDER_CAPABILITY_UNSPECIFIED",
		1: "PROVIDER_CAPABILITY_SEARCH",
		2: "PROVIDER_CAPABILITY_STREAM_TRACK",
		3: "PROVIDER_CAPABILITY_LIBRARY_MANAGEMENT",
	}
	ProviderCapability_value = map[string]int32{
		"PROVIDER_CAPABILITY_UNSPECIFIED":        0,
		"PROVIDER_CAPABILITY_SEARCH":             1,
		"PROVIDER_CAPABILITY_STREAM_TRACK":       2,
		"PROVIDER_CAPABILITY_LIBRARY_MANAGEMENT": 3,
	}
)

func (x ProviderCapability) Enum() *ProviderCapability {
	p := new(ProviderCapability)
	*p = x
	return p
}

func (x ProviderCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_api_music_v1_music_provider_proto_enumTypes[0].Descriptor()
}

func (ProviderCapability) Type() protoreflect.EnumType {
	return &file_api_music_v1_music_provider_proto_enumTypes[0]
}

func (x ProviderCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderCapability.Descriptor instead.
func (ProviderCapability) EnumDescriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{0}
}

type AuthStatus int32

const (
	AuthStatus_AUTH_STATUS_UNSPECIFIED     AuthStatus = 0
	AuthStatus_AUTH_STATUS_UNAUTHENTICATED AuthStatus = 1
	AuthStatus_AUTH_STATUS_AUTHENTICATED   AuthStatus = 2
	AuthStatus_AUTH_STATUS_EXPIRED         AuthStatus = 3
)

// Enum value maps for AuthStatus.
var (
	AuthStatus_name = map[int32]string{
		0: "AUTH_STATUS_UNSPECIFIED",
		1: "AUTH_STATUS_UNAUTHENTICATED",
		2: "AUTH_STATUS_AUTHENTICATED",
		3: "AUTH_STATUS_EXPIRED",
	}
	AuthStatus_value = map[string]int32{
		"AUTH_STATUS_UNSPECIFIED":     0,
		"AUTH_STATUS_UNAUTHENTICATED": 1,
		"AUTH_STATUS_AUTHENTICATED":   2,
		"AUTH_STATUS_EXPIRED":         3,
	}
)

func (x AuthStatus) Enum() *AuthStatus {
	p := new(AuthStatus)
	*p = x
	return p
}

func (x AuthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_music_v1_music_provider_proto_enumTypes[1].Descriptor()
}

func (AuthStatus) Type() protoreflect.EnumType {
	return &file_api_music_v1_music_provider_proto_enumTypes[1]
}

func (x AuthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthStatus.Descriptor instead.
func (AuthStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{1}
}

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_TRACK       MediaType = 1
	MediaType_MEDIA_TYPE_ALBUM       MediaType = 2
	MediaType_MEDIA_TYPE_ARTIST      MediaType = 3
	MediaType_MEDIA_TYPE_PLAYLIST    MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_TRACK",
		2: "MEDIA_TYPE_ALBUM",
		3: "MEDIA_TYPE_ARTIST",
		4: "MEDIA_TYPE_PLAYLIST",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_TRACK":       1,
		"MEDIA_TYPE_ALBUM":       2,
		"MEDIA_TYPE_ARTIST":      3,
		"MEDIA_TYPE_PLAYLIST":    4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_music_v1_music_provider_proto_enumTypes[2].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_api_music_v1_music_provider_proto_enumTypes[2]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{2}
}

type AudioQuality int32

const (
	AudioQuality_AUDIO_QUALITY_UNSPECIFIED AudioQuality = 0
	AudioQuality_AUDIO_QUALITY_LOW         AudioQuality = 1
	AudioQuality_AUDIO_QUALITY_MEDIUM      AudioQuality = 2
	AudioQuality_AUDIO_QUALITY_HIGH        AudioQuality = 3
)

// Enum value maps for AudioQuality.
var (
	AudioQuality_name = map[int32]string{
		0: "AUDIO_QUALITY_UNSPECIFIED",
		1: "AUDIO_QUALITY_LOW",
		2: "AUDIO_QUALITY_MEDIUM",
		3: "AUDIO_QUALITY_HIGH",
	}
	AudioQuality_value = map[string]int32{
		"AUDIO_QUALITY_UNSPECIFIED": 0,
		"AUDIO_QUALITY_LOW":         1,
		"AUDIO_QUALITY_MEDIUM":      2,
		"AUDIO_QUALITY_HIGH":        3,
	}
)

func (x AudioQuality) Enum() *AudioQuality {
	p := new(AudioQuality)
	*p = x
	return p
}

func (x AudioQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_api_music_v1_music_provider_proto_enumTypes[3].Descriptor()
}

func (AudioQuality) Type() protoreflect.EnumType {
	return &file_api_music_v1_music_provider_proto_enumTypes[3]
}

func (x AudioQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioQuality.Descriptor instead.
func (AudioQuality) EnumDescriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{3}
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Artist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artist) Reset() {
	*x = Artist{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artist) ProtoMessage() {}

func (x *Artist) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artist.ProtoReflect.Descriptor instead.
func (*Artist) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{1}
}

func (x *Artist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Artist) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Album struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artists       []*Artist              `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	Images        []*Image               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	ReleaseYear   int32                  `protobuf:"varint,5,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	TrackCount    int32                  `protobuf:"varint,6,opt,name=track_count,json=trackCount,proto3" json:"track_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Album) Reset() {
	*x = Album{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Album) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Album) ProtoMessage() {}

func (x *Album) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Album.ProtoReflect.Descriptor instead.
func (*Album) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{2}
}

func (x *Album) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Album) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Album) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Album) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Album) GetReleaseYear() int32 {
	if x != nil {
		return x.ReleaseYear
	}
	return 0
}

func (x *Album) GetTrackCount() int32 {
	if x != nil {
		return x.TrackCount
	}
	return 0
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artists       []*Artist              `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	Album         *Album                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	DurationMs    int64                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Images        []*Image               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	Explicit      bool                   `protobuf:"varint,7,opt,name=explicit,proto3" json:"explicit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{3}
}

func (x *Track) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *Track) GetAlbum() *Album {
	if x != nil {
		return x.Album
	}
	return nil
}

func (x *Track) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *Track) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Track) GetExplicit() bool {
	if x != nil {
		return x.Explicit
	}
	return false
}

type Playlist struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerName     string                 `protobuf:"bytes,4,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Images        []*Image               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	TrackCount    int32                  `protobuf:"varint,6,opt,name=track_count,json=trackCount,proto3" json:"track_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Playlist) Reset() {
	*x = Playlist{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Playlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Playlist) ProtoMessage() {}

func (x *Playlist) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Playlist.ProtoReflect.Descriptor instead.
func (*Playlist) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{4}
}

func (x *Playlist) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Playlist) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Playlist) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Playlist) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *Playlist) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Playlist) GetTrackCount() int32 {
	if x != nil {
		return x.TrackCount
	}
	return 0
}

type GetProviderMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderMetadataRequest) Reset() {
	*x = GetProviderMetadataRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderMetadataRequest) ProtoMessage() {}

func (x *GetProviderMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderMetadataRequest.ProtoReflect.Descriptor instead.
func (*GetProviderMetadataRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{5}
}

type GetProviderMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Capabilities  []ProviderCapability   `protobuf:"varint,3,rep,packed,name=capabilities,proto3,enum=music.v1.ProviderCapability" json:"capabilities,omitempty"`
	AuthStatus    AuthStatus             `protobuf:"varint,4,opt,name=auth_status,json=authStatus,proto3,enum=music.v1.AuthStatus" json:"auth_status,omitempty"`
	AuthUrl       string                 `protobuf:"bytes,5,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProviderMetadataResponse) Reset() {
	*x = GetProviderMetadataResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProviderMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProviderMetadataResponse) ProtoMessage() {}

func (x *GetProviderMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProviderMetadataResponse.ProtoReflect.Descriptor instead.
func (*GetProviderMetadataResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{6}
}

func (x *GetProviderMetadataResponse) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *GetProviderMetadataResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *GetProviderMetadataResponse) GetCapabilities() []ProviderCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetProviderMetadataResponse) GetAuthStatus() AuthStatus {
	if x != nil {
		return x.AuthStatus
	}
	return AuthStatus_AUTH_STATUS_UNSPECIFIED
}

func (x *GetProviderMetadataResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

type InitiateAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional provider-specific parameters. For spotify this can carry a
	// client_id so the user does not have to set it via environment variables.
	Params        map[string]string `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateAuthRequest) Reset() {
	*x = InitiateAuthRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateAuthRequest) ProtoMessage() {}

func (x *InitiateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateAuthRequest.ProtoReflect.Descriptor instead.
func (*InitiateAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{7}
}

func (x *InitiateAuthRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type InitiateAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	DeviceCode    string                 `protobuf:"bytes,2,opt,name=device_code,json=deviceCode,proto3" json:"device_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateAuthResponse) Reset() {
	*x = InitiateAuthResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateAuthResponse) ProtoMessage() {}

func (x *InitiateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateAuthResponse.ProtoReflect.Descriptor instead.
func (*InitiateAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{8}
}

func (x *InitiateAuthResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *InitiateAuthResponse) GetDeviceCode() string {
	if x != nil {
		return x.DeviceCode
	}
	return ""
}

type CompleteAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        map[string]string      `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthRequest) Reset() {
	*x = CompleteAuthRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthRequest) ProtoMessage() {}

func (x *CompleteAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthRequest.ProtoReflect.Descriptor instead.
func (*CompleteAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{9}
}

func (x *CompleteAuthRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

type CompleteAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteAuthResponse) Reset() {
	*x = CompleteAuthResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteAuthResponse) ProtoMessage() {}

func (x *CompleteAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteAuthResponse.ProtoReflect.Descriptor instead.
func (*CompleteAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{10}
}

func (x *CompleteAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CompleteAuthResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CompleteAuthResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type RefreshAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthRequest) Reset() {
	*x = RefreshAuthRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthRequest) ProtoMessage() {}

func (x *RefreshAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthRequest.ProtoReflect.Descriptor instead.
func (*RefreshAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshAuthRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAuthResponse) Reset() {
	*x = RefreshAuthResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAuthResponse) ProtoMessage() {}

func (x *RefreshAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAuthResponse.ProtoReflect.Descriptor instead.
func (*RefreshAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshAuthResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshAuthResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Types         []MediaType            `protobuf:"varint,2,rep,packed,name=types,proto3,enum=music.v1.MediaType" json:"types,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{13}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetTypes() []MediaType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Albums        []*Album               `protobuf:"bytes,2,rep,name=albums,proto3" json:"albums,omitempty"`
	Artists       []*Artist              `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	Playlists     []*Playlist            `protobuf:"bytes,4,rep,name=playlists,proto3" json:"playlists,omitempty"`
	NextPageToken string                 `protobuf:"bytes,5,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{14}
}

func (x *SearchResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *SearchResponse) GetAlbums() []*Album {
	if x != nil {
		return x.Albums
	}
	return nil
}

func (x *SearchResponse) GetArtists() []*Artist {
	if x != nil {
		return x.Artists
	}
	return nil
}

func (x *SearchResponse) GetPlaylists() []*Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

func (x *SearchResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type SearchSuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSuggestionsRequest) Reset() {
	*x = SearchSuggestionsRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSuggestionsRequest) ProtoMessage() {}

func (x *SearchSuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSuggestionsRequest.ProtoReflect.Descriptor instead.
func (*SearchSuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{15}
}

func (x *SearchSuggestionsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchSuggestionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchSuggestionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestion    string                 `protobuf:"bytes,1,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	Type          MediaType              `protobuf:"varint,2,opt,name=type,proto3,enum=music.v1.MediaType" json:"type,omitempty"`
	RelatedId     string                 `protobuf:"bytes,3,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchSuggestionsResponse) Reset() {
	*x = SearchSuggestionsResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSuggestionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSuggestionsResponse) ProtoMessage() {}

func (x *SearchSuggestionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSuggestionsResponse.ProtoReflect.Descriptor instead.
func (*SearchSuggestionsResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{16}
}

func (x *SearchSuggestionsResponse) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *SearchSuggestionsResponse) GetType() MediaType {
	if x != nil {
		return x.Type
	}
	return MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *SearchSuggestionsResponse) GetRelatedId() string {
	if x != nil {
		return x.RelatedId
	}
	return ""
}

type GetTrackDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TrackId       string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackDetailsRequest) Reset() {
	*x = GetTrackDetailsRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackDetailsRequest) ProtoMessage() {}

func (x *GetTrackDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetTrackDetailsRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{17}
}

func (x *GetTrackDetailsRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

type GetTrackDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrackDetailsResponse) Reset() {
	*x = GetTrackDetailsResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrackDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrackDetailsResponse) ProtoMessage() {}

func (x *GetTrackDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrackDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetTrackDetailsResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{18}
}

func (x *GetTrackDetailsResponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type ResolveStreamRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrackId          string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	PreferredQuality AudioQuality           `protobuf:"varint,2,opt,name=preferred_quality,json=preferredQuality,proto3,enum=music.v1.AudioQuality" json:"preferred_quality,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResolveStreamRequest) Reset() {
	*x = ResolveStreamRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveStreamRequest) ProtoMessage() {}

func (x *ResolveStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveStreamRequest.ProtoReflect.Descriptor instead.
func (*ResolveStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{19}
}

func (x *ResolveStreamRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *ResolveStreamRequest) GetPreferredQuality() AudioQuality {
	if x != nil {
		return x.PreferredQuality
	}
	return AudioQuality_AUDIO_QUALITY_UNSPECIFIED
}

type ResolveStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExpiryMs      int64                  `protobuf:"varint,3,opt,name=expiry_ms,json=expiryMs,proto3" json:"expiry_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveStreamResponse) Reset() {
	*x = ResolveStreamResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveStreamResponse) ProtoMessage() {}

func (x *ResolveStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveStreamResponse.ProtoReflect.Descriptor instead.
func (*ResolveStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{20}
}

func (x *ResolveStreamResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

func (x *ResolveStreamResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ResolveStreamResponse) GetExpiryMs() int64 {
	if x != nil {
		return x.ExpiryMs
	}
	return 0
}

type StreamAudioRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TrackId         string                 `protobuf:"bytes,1,opt,name=track_id,json=trackId,proto3" json:"track_id,omitempty"`
	Quality         AudioQuality           `protobuf:"varint,2,opt,name=quality,proto3,enum=music.v1.AudioQuality" json:"quality,omitempty"`
	StartPositionMs int64                  `protobuf:"varint,3,opt,name=start_position_ms,json=startPositionMs,proto3" json:"start_position_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamAudioRequest) Reset() {
	*x = StreamAudioRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAudioRequest) ProtoMessage() {}

func (x *StreamAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAudioRequest.ProtoReflect.Descriptor instead.
func (*StreamAudioRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{21}
}

func (x *StreamAudioRequest) GetTrackId() string {
	if x != nil {
		return x.TrackId
	}
	return ""
}

func (x *StreamAudioRequest) GetQuality() AudioQuality {
	if x != nil {
		return x.Quality
	}
	return AudioQuality_AUDIO_QUALITY_UNSPECIFIED
}

func (x *StreamAudioRequest) GetStartPositionMs() int64 {
	if x != nil {
		return x.StartPositionMs
	}
	return 0
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Eof           bool                   `protobuf:"varint,3,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{22}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AudioChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type GetUserLibraryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLibraryRequest) Reset() {
	*x = GetUserLibraryRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLibraryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLibraryRequest) ProtoMessage() {}

func (x *GetUserLibraryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLibraryRequest.ProtoReflect.Descriptor instead.
func (*GetUserLibraryRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{23}
}

func (x *GetUserLibraryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserLibraryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetUserLibraryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLibraryResponse) Reset() {
	*x = GetUserLibraryResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLibraryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLibraryResponse) ProtoMessage() {}

func (x *GetUserLibraryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLibraryResponse.ProtoReflect.Descriptor instead.
func (*GetUserLibraryResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{24}
}

func (x *GetUserLibraryResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *GetUserLibraryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetUserPlaylistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPlaylistsRequest) Reset() {
	*x = GetUserPlaylistsRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPlaylistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlaylistsRequest) ProtoMessage() {}

func (x *GetUserPlaylistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlaylistsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPlaylistsRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{25}
}

func (x *GetUserPlaylistsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserPlaylistsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetUserPlaylistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlists     []*Playlist            `protobuf:"bytes,1,rep,name=playlists,proto3" json:"playlists,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPlaylistsResponse) Reset() {
	*x = GetUserPlaylistsResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPlaylistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPlaylistsResponse) ProtoMessage() {}

func (x *GetUserPlaylistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPlaylistsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPlaylistsResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{26}
}

func (x *GetUserPlaylistsResponse) GetPlaylists() []*Playlist {
	if x != nil {
		return x.Playlists
	}
	return nil
}

func (x *GetUserPlaylistsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type GetPlaylistDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlaylistId    string                 `protobuf:"bytes,1,opt,name=playlist_id,json=playlistId,proto3" json:"playlist_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistDetailsRequest) Reset() {
	*x = GetPlaylistDetailsRequest{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistDetailsRequest) ProtoMessage() {}

func (x *GetPlaylistDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetPlaylistDetailsRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{27}
}

func (x *GetPlaylistDetailsRequest) GetPlaylistId() string {
	if x != nil {
		return x.PlaylistId
	}
	return ""
}

func (x *GetPlaylistDetailsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetPlaylistDetailsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetPlaylistDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playlist      *Playlist              `protobuf:"bytes,1,opt,name=playlist,proto3" json:"playlist,omitempty"`
	Tracks        []*Track               `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	NextPageToken string                 `protobuf:"bytes,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlaylistDetailsResponse) Reset() {
	*x = GetPlaylistDetailsResponse{}
	mi := &file_api_music_v1_music_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlaylistDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlaylistDetailsResponse) ProtoMessage() {}

func (x *GetPlaylistDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_music_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlaylistDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetPlaylistDetailsResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_music_provider_proto_rawDescGZIP(), []int{28}
}

func (x *GetPlaylistDetailsResponse) GetPlaylist() *Playlist {
	if x != nil {
		return x.Playlist
	}
	return nil
}

func (x *GetPlaylistDetailsResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *GetPlaylistDetailsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_api_music_v1_music_provider_proto protoreflect.FileDescriptor

const file_api_music_v1_music_provider_proto_rawDesc = "" +
	"\n" +
	"!api/music/v1/music_provider.proto\x12\bmusic.v1\"G\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\",\n" +
	"\x06Artist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xc6\x01\n" +
	"\x05Album\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\aartists\x18\x03 \x03(\v2\x10.music.v1.ArtistR\aartists\x12'\n" +
	"\x06images\x18\x04 \x03(\v2\x0f.music.v1.ImageR\x06images\x12!\n" +
	"\frelease_year\x18\x05 \x01(\x05R\vreleaseYear\x12\x1f\n" +
	"\vtrack_count\x18\x06 \x01(\x05R\n" +
	"trackCount\"\xe6\x01\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12*\n" +
	"\aartists\x18\x03 \x03(\v2\x10.music.v1.ArtistR\aartists\x12%\n" +
	"\x05album\x18\x04 \x01(\v2\x0f.music.v1.AlbumR\x05album\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x03R\n" +
	"durationMs\x12'\n" +
	"\x06images\x18\x06 \x03(\v2\x0f.music.v1.ImageR\x06images\x12\x1a\n" +
	"\bexplicit\x18\a \x01(\bR\bexplicit\"\xbb\x01\n" +
	"\bPlaylist\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x04 \x01(\tR\townerName\x12'\n" +
	"\x06images\x18\x05 \x03(\v2\x0f.music.v1.ImageR\x06images\x12\x1f\n" +
	"\vtrack_count\x18\x06 \x01(\x05R\n" +
	"trackCount\"\x1c\n" +
	"\x1aGetProviderMetadataRequest\"\xf5\x01\n" +
	"\x1bGetProviderMetadataResponse\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12@\n" +
	"\fcapabilities\x18\x03 \x03(\x0e2\x1c.music.v1.ProviderCapabilityR\fcapabilities\x125\n" +
	"\vauth_status\x18\x04 \x01(\x0e2\x14.music.v1.AuthStatusR\n" +
	"authStatus\x12\x19\n" +
	"\bauth_url\x18\x05 \x01(\tR\aauthUrl\"\x93\x01\n" +
	"\x13InitiateAuthRequest\x12A\n" +
	"\x06params\x18\x01 \x03(\v2).music.v1.InitiateAuthRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x14InitiateAuthResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x1f\n" +
	"\vdevice_code\x18\x02 \x01(\tR\n" +
	"deviceCode\"\x93\x01\n" +
	"\x13CompleteAuthRequest\x12A\n" +
	"\x06params\x18\x01 \x03(\v2).music.v1.CompleteAuthRequest.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"}\n" +
	"\x14CompleteAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\"9\n" +
	"\x12RefreshAuthRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"W\n" +
	"\x13RefreshAuthResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"\x85\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12)\n" +
	"\x05types\x18\x02 \x03(\x0e2\x13.music.v1.MediaTypeR\x05types\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xe8\x01\n" +
	"\x0eSearchResponse\x12'\n" +
	"\x06tracks\x18\x01 \x03(\v2\x0f.music.v1.TrackR\x06tracks\x12'\n" +
	"\x06albums\x18\x02 \x03(\v2\x0f.music.v1.AlbumR\x06albums\x12*\n" +
	"\aartists\x18\x03 \x03(\v2\x10.music.v1.ArtistR\aartists\x120\n" +
	"\tplaylists\x18\x04 \x03(\v2\x12.music.v1.PlaylistR\tplaylists\x12&\n" +
	"\x0fnext_page_token\x18\x05 \x01(\tR\rnextPageToken\"F\n" +
	"\x18SearchSuggestionsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x83\x01\n" +
	"\x19SearchSuggestionsResponse\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x01 \x01(\tR\n" +
	"suggestion\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.music.v1.MediaTypeR\x04type\x12\x1d\n" +
	"\n" +
	"related_id\x18\x03 \x01(\tR\trelatedId\"3\n" +
	"\x16GetTrackDetailsRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\"@\n" +
	"\x17GetTrackDetailsResponse\x12%\n" +
	"\x05track\x18\x01 \x01(\v2\x0f.music.v1.TrackR\x05track\"v\n" +
	"\x14ResolveStreamRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x12C\n" +
	"\x11preferred_quality\x18\x02 \x01(\x0e2\x16.music.v1.AudioQualityR\x10preferredQuality\"\xd7\x01\n" +
	"\x15ResolveStreamResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\x12F\n" +
	"\aheaders\x18\x02 \x03(\v2,.music.v1.ResolveStreamResponse.HeadersEntryR\aheaders\x12\x1b\n" +
	"\texpiry_ms\x18\x03 \x01(\x03R\bexpiryMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x12StreamAudioRequest\x12\x19\n" +
	"\btrack_id\x18\x01 \x01(\tR\atrackId\x120\n" +
	"\aquality\x18\x02 \x01(\x0e2\x16.music.v1.AudioQualityR\aquality\x12*\n" +
	"\x11start_position_ms\x18\x03 \x01(\x03R\x0fstartPositionMs\"U\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12\x10\n" +
	"\x03eof\x18\x03 \x01(\bR\x03eof\"L\n" +
	"\x15GetUserLibraryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"i\n" +
	"\x16GetUserLibraryResponse\x12'\n" +
	"\x06tracks\x18\x01 \x03(\v2\x0f.music.v1.TrackR\x06tracks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"N\n" +
	"\x17GetUserPlaylistsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"t\n" +
	"\x18GetUserPlaylistsResponse\x120\n" +
	"\tplaylists\x18\x01 \x03(\v2\x12.music.v1.PlaylistR\tplaylists\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"q\n" +
	"\x19GetPlaylistDetailsRequest\x12\x1f\n" +
	"\vplaylist_id\x18\x01 \x01(\tR\n" +
	"playlistId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x9d\x01\n" +
	"\x1aGetPlaylistDetailsResponse\x12.\n" +
	"\bplaylist\x18\x01 \x01(\v2\x12.music.v1.PlaylistR\bplaylist\x12'\n" +
	"\x06tracks\x18\x02 \x03(\v2\x0f.music.v1.TrackR\x06tracks\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\tR\rnextPageToken*\xab\x01\n" +
	"\x12ProviderCapability\x12#\n" +
	"\x1fPROVIDER_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aPROVIDER_CAPABILITY_SEARCH\x10\x01\x12$\n" +
	" PROVIDER_CAPABILITY_STREAM_TRACK\x10\x02\x12*\n" +
	"&PROVIDER_CAPABILITY_LIBRARY_MANAGEMENT\x10\x03*\x82\x01\n" +
	"\n" +
	"AuthStatus\x12\x1b\n" +
	"\x17AUTH_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bAUTH_STATUS_UNAUTHENTICATED\x10\x01\x12\x1d\n" +
	"\x19AUTH_STATUS_AUTHENTICATED\x10\x02\x12\x17\n" +
	"\x13AUTH_STATUS_EXPIRED\x10\x03*\x83\x01\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_TRACK\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_ALBUM\x10\x02\x12\x15\n" +
	"\x11MEDIA_TYPE_ARTIST\x10\x03\x12\x17\n" +
	"\x13MEDIA_TYPE_PLAYLIST\x10\x04*v\n" +
	"\fAudioQuality\x12\x1d\n" +
	"\x19AUDIO_QUALITY_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11AUDIO_QUALITY_LOW\x10\x01\x12\x18\n" +
	"\x14AUDIO_QUALITY_MEDIUM\x10\x02\x12\x16\n" +
	"\x12AUDIO_QUALITY_HIGH\x10\x032\x81\b\n" +
	"\x14MusicProviderService\x12b\n" +
	"\x13GetProviderMetadata\x12$.music.v1.GetProviderMetadataRequest\x1a%.music.v1.GetProviderMetadataResponse\x12M\n" +
	"\fInitiateAuth\x12\x1d.music.v1.InitiateAuthRequest\x1a\x1e.music.v1.InitiateAuthResponse\x12M\n" +
	"\fCompleteAuth\x12\x1d.music.v1.CompleteAuthRequest\x1a\x1e.music.v1.CompleteAuthResponse\x12J\n" +
	"\vRefreshAuth\x12\x1c.music.v1.RefreshAuthRequest\x1a\x1d.music.v1.RefreshAuthResponse\x12;\n" +
	"\x06Search\x12\x17.music.v1.SearchRequest\x1a\x18.music.v1.SearchResponse\x12^\n" +
	"\x11SearchSuggestions\x12\".music.v1.SearchSuggestionsRequest\x1a#.music.v1.SearchSuggestionsResponse0\x01\x12V\n" +
	"\x0fGetTrackDetails\x12 .music.v1.GetTrackDetailsRequest\x1a!.music.v1.GetTrackDetailsResponse\x12P\n" +
	"\rResolveStream\x12\x1e.music.v1.ResolveStreamRequest\x1a\x1f.music.v1.ResolveStreamResponse\x12C\n" +
	"\vStreamAudio\x12\x1c.music.v1.StreamAudioRequest\x1a\x14.music.v1.AudioChunk0\x01\x12S\n" +
	"\x0eGetUserLibrary\x12\x1f.music.v1.GetUserLibraryRequest\x1a .music.v1.GetUserLibraryResponse\x12Y\n" +
	"\x10GetUserPlaylists\x12!.music.v1.GetUserPlaylistsRequest\x1a\".music.v1.GetUserPlaylistsResponse\x12_\n" +
	"\x12GetPlaylistDetails\x12#.music.v1.GetPlaylistDetailsRequest\x1a$.music.v1.GetPlaylistDetailsResponseB-Z+github.com/gg582/gozik/api/music/v1;musicv1b\x06proto3"

var (
	file_api_music_v1_music_provider_proto_rawDescOnce sync.Once
	file_api_music_v1_music_provider_proto_rawDescData []byte
)

func file_api_music_v1_music_provider_proto_rawDescGZIP() []byte {
	file_api_music_v1_music_provider_proto_rawDescOnce.Do(func() {
		file_api_music_v1_music_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_music_v1_music_provider_proto_rawDesc), len(file_api_music_v1_music_provider_proto_rawDesc)))
	})
	return file_api_music_v1_music_provider_proto_rawDescData
}

var file_api_music_v1_music_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_api_music_v1_music_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_api_music_v1_music_provider_proto_goTypes = []any{
	(ProviderCapability)(0),             // 0: music.v1.ProviderCapability
	(AuthStatus)(0),                     // 1: music.v1.AuthStatus
	(MediaType)(0),                      // 2: music.v1.MediaType
	(AudioQuality)(0),                   // 3: music.v1.AudioQuality
	(*Image)(nil),                       // 4: music.v1.Image
	(*Artist)(nil),                      // 5: music.v1.Artist
	(*Album)(nil),                       // 6: music.v1.Album
	(*Track)(nil),                       // 7: music.v1.Track
	(*Playlist)(nil),                    // 8: music.v1.Playlist
	(*GetProviderMetadataRequest)(nil),  // 9: music.v1.GetProviderMetadataRequest
	(*GetProviderMetadataResponse)(nil), // 10: music.v1.GetProviderMetadataResponse
	(*InitiateAuthRequest)(nil),         // 11: music.v1.InitiateAuthRequest
	(*InitiateAuthResponse)(nil),        // 12: music.v1.InitiateAuthResponse
	(*CompleteAuthRequest)(nil),         // 13: music.v1.CompleteAuthRequest
	(*CompleteAuthResponse)(nil),        // 14: music.v1.CompleteAuthResponse
	(*RefreshAuthRequest)(nil),          // 15: music.v1.RefreshAuthRequest
	(*RefreshAuthResponse)(nil),         // 16: music.v1.RefreshAuthResponse
	(*SearchRequest)(nil),               // 17: music.v1.SearchRequest
	(*SearchResponse)(nil),              // 18: music.v1.SearchResponse
	(*SearchSuggestionsRequest)(nil),    // 19: music.v1.SearchSuggestionsRequest
	(*SearchSuggestionsResponse)(nil),   // 20: music.v1.SearchSuggestionsResponse
	(*GetTrackDetailsRequest)(nil),      // 21: music.v1.GetTrackDetailsRequest
	(*GetTrackDetailsResponse)(nil),     // 22: music.v1.GetTrackDetailsResponse
	(*ResolveStreamRequest)(nil),        // 23: music.v1.ResolveStreamRequest
	(*ResolveStreamResponse)(nil),       // 24: music.v1.ResolveStreamResponse
	(*StreamAudioRequest)(nil),          // 25: music.v1.StreamAudioRequest
	(*AudioChunk)(nil),                  // 26: music.v1.AudioChunk
	(*GetUserLibraryRequest)(nil),       // 27: music.v1.GetUserLibraryRequest
	(*GetUserLibraryResponse)(nil),      // 28: music.v1.GetUserLibraryResponse
	(*GetUserPlaylistsRequest)(nil),     // 29: music.v1.GetUserPlaylistsRequest
	(*GetUserPlaylistsResponse)(nil),    // 30: music.v1.GetUserPlaylistsResponse
	(*GetPlaylistDetailsRequest)(nil),   // 31: music.v1.GetPlaylistDetailsRequest
	(*GetPlaylistDetailsResponse)(nil),  // 32: music.v1.GetPlaylistDetailsResponse
	nil,                                 // 33: music.v1.InitiateAuthRequest.ParamsEntry
	nil,                                 // 34: music.v1.CompleteAuthRequest.ParamsEntry
	nil,                                 // 35: music.v1.ResolveStreamResponse.HeadersEntry
}
var file_api_music_v1_music_provider_proto_depIdxs = []int32{
	5,  // 0: music.v1.Album.artists:type_name -> music.v1.Artist
	4,  // 1: music.v1.Album.images:type_name -> music.v1.Image
	5,  // 2: music.v1.Track.artists:type_name -> music.v1.Artist
	6,  // 3: music.v1.Track.album:type_name -> music.v1.Album
	4,  // 4: music.v1.Track.images:type_name -> music.v1.Image
	4,  // 5: music.v1.Playlist.images:type_name -> music.v1.Image
	0,  // 6: music.v1.GetProviderMetadataResponse.capabilities:type_name -> music.v1.ProviderCapability
	1,  // 7: music.v1.GetProviderMetadataResponse.auth_status:type_name -> music.v1.AuthStatus
	33, // 8: music.v1.InitiateAuthRequest.params:type_name -> music.v1.InitiateAuthRequest.ParamsEntry
	34, // 9: music.v1.CompleteAuthRequest.params:type_name -> music.v1.CompleteAuthRequest.ParamsEntry
	2,  // 10: music.v1.SearchRequest.types:type_name -> music.v1.MediaType
	7,  // 11: music.v1.SearchResponse.tracks:type_name -> music.v1.Track
	6,  // 12: music.v1.SearchResponse.albums:type_name -> music.v1.Album
	5,  // 13: music.v1.SearchResponse.artists:type_name -> music.v1.Artist
	8,  // 14: music.v1.SearchResponse.playlists:type_name -> music.v1.Playlist
	2,  // 15: music.v1.SearchSuggestionsResponse.type:type_name -> music.v1.MediaType
	7,  // 16: music.v1.GetTrackDetailsResponse.track:type_name -> music.v1.Track
	3,  // 17: music.v1.ResolveStreamRequest.preferred_quality:type_name -> music.v1.AudioQuality
	35, // 18: music.v1.ResolveStreamResponse.headers:type_name -> music.v1.ResolveStreamResponse.HeadersEntry
	3,  // 19: music.v1.StreamAudioRequest.quality:type_name -> music.v1.AudioQuality
	7,  // 20: music.v1.GetUserLibraryResponse.tracks:type_name -> music.v1.Track
	8,  // 21: music.v1.GetUserPlaylistsResponse.playlists:type_name -> music.v1.Playlist
	8,  // 22: music.v1.GetPlaylistDetailsResponse.playlist:type_name -> music.v1.Playlist
	7,  // 23: music.v1.GetPlaylistDetailsResponse.tracks:type_name -> music.v1.Track
	9,  // 24: music.v1.MusicProviderService.GetProviderMetadata:input_type -> music.v1.GetProviderMetadataRequest
	11, // 25: music.v1.MusicProviderService.InitiateAuth:input_type -> music.v1.InitiateAuthRequest
	13, // 26: music.v1.MusicProviderService.CompleteAuth:input_type -> music.v1.CompleteAuthRequest
	15, // 27: music.v1.MusicProviderService.RefreshAuth:input_type -> music.v1.RefreshAuthRequest
	17, // 28: music.v1.MusicProviderService.Search:input_type -> music.v1.SearchRequest
	19, // 29: music.v1.MusicProviderService.SearchSuggestions:input_type -> music.v1.SearchSuggestionsRequest
	21, // 30: music.v1.MusicProviderService.GetTrackDetails:input_type -> music.v1.GetTrackDetailsRequest
	23, // 31: music.v1.MusicProviderService.ResolveStream:input_type -> music.v1.ResolveStreamRequest
	25, // 32: music.v1.MusicProviderService.StreamAudio:input_type -> music.v1.StreamAudioRequest
	27, // 33: music.v1.MusicProviderService.GetUserLibrary:input_type -> music.v1.GetUserLibraryRequest
	29, // 34: music.v1.MusicProviderService.GetUserPlaylists:input_type -> music.v1.GetUserPlaylistsRequest
	31, // 35: music.v1.MusicProviderService.GetPlaylistDetails:input_type -> music.v1.GetPlaylistDetailsRequest
	10, // 36: music.v1.MusicProviderService.GetProviderMetadata:output_type -> music.v1.GetProviderMetadataResponse
	12, // 37: music.v1.MusicProviderService.InitiateAuth:output_type -> music.v1.InitiateAuthResponse
	14, // 38: music.v1.MusicProviderService.CompleteAuth:output_type -> music.v1.CompleteAuthResponse
	16, // 39: music.v1.MusicProviderService.RefreshAuth:output_type -> music.v1.RefreshAuthResponse
	18, // 40: music.v1.MusicProviderService.Search:output_type -> music.v1.SearchResponse
	20, // 41: music.v1.MusicProviderService.SearchSuggestions:output_type -> music.v1.SearchSuggestionsResponse
	22, // 42: music.v1.MusicProviderService.GetTrackDetails:output_type -> music.v1.GetTrackDetailsResponse
	24, // 43: music.v1.MusicProviderService.ResolveStream:output_type -> music.v1.ResolveStreamResponse
	26, // 44: music.v1.MusicProviderService.StreamAudio:output_type -> music.v1.AudioChunk
	28, // 45: music.v1.MusicProviderService.GetUserLibrary:output_type -> music.v1.GetUserLibraryResponse
	30, // 46: music.v1.MusicProviderService.GetUserPlaylists:output_type -> music.v1.GetUserPlaylistsResponse
	32, // 47: music.v1.MusicProviderService.GetPlaylistDetails:output_type -> music.v1.GetPlaylistDetailsResponse
	36, // [36:48] is the sub-list for method output_type
	24, // [24:36] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_api_music_v1_music_provider_proto_init() }
func file_api_music_v1_music_provider_proto_init() {
	if File_api_music_v1_music_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_music_v1_music_provider_proto_rawDesc), len(file_api_music_v1_music_provider_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_music_v1_music_provider_proto_goTypes,
		DependencyIndexes: file_api_music_v1_music_provider_proto_depIdxs,
		EnumInfos:         file_api_music_v1_music_provider_proto_enumTypes,
		MessageInfos:      file_api_music_v1_music_provider_proto_msgTypes,
	}.Build()
	File_api_music_v1_music_provider_proto = out.File
	file_api_music_v1_music_provider_proto_goTypes = nil
	file_api_music_v1_music_provider_proto_depIdxs = nil
}
