// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: api/music/v1/provider_link.proto

package musicv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginStatus int32

const (
	PluginStatus_PLUGIN_STATUS_UNSPECIFIED PluginStatus = 0
	PluginStatus_PLUGIN_STATUS_READY       PluginStatus = 1
	PluginStatus_PLUGIN_STATUS_LINKED      PluginStatus = 2
	PluginStatus_PLUGIN_STATUS_ERROR       PluginStatus = 3
)

// Enum value maps for PluginStatus.
var (
	PluginStatus_name = map[int32]string{
		0: "PLUGIN_STATUS_UNSPECIFIED",
		1: "PLUGIN_STATUS_READY",
		2: "PLUGIN_STATUS_LINKED",
		3: "PLUGIN_STATUS_ERROR",
	}
	PluginStatus_value = map[string]int32{
		"PLUGIN_STATUS_UNSPECIFIED": 0,
		"PLUGIN_STATUS_READY":       1,
		"PLUGIN_STATUS_LINKED":      2,
		"PLUGIN_STATUS_ERROR":       3,
	}
)

func (x PluginStatus) Enum() *PluginStatus {
	p := new(PluginStatus)
	*p = x
	return p
}

func (x PluginStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_music_v1_provider_link_proto_enumTypes[0].Descriptor()
}

func (PluginStatus) Type() protoreflect.EnumType {
	return &file_api_music_v1_provider_link_proto_enumTypes[0]
}

func (x PluginStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginStatus.Descriptor instead.
func (PluginStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{0}
}

type PluginProvider struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	IconUrl       string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Status        PluginStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=music.v1.PluginStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginProvider) Reset() {
	*x = PluginProvider{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginProvider) ProtoMessage() {}

func (x *PluginProvider) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginProvider.ProtoReflect.Descriptor instead.
func (*PluginProvider) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{0}
}

func (x *PluginProvider) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginProvider) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PluginProvider) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PluginProvider) GetStatus() PluginStatus {
	if x != nil {
		return x.Status
	}
	return PluginStatus_PLUGIN_STATUS_UNSPECIFIED
}

type ListAvailablePluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailablePluginsRequest) Reset() {
	*x = ListAvailablePluginsRequest{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailablePluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailablePluginsRequest) ProtoMessage() {}

func (x *ListAvailablePluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailablePluginsRequest.ProtoReflect.Descriptor instead.
func (*ListAvailablePluginsRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{1}
}

type ListAvailablePluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginProvider      `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAvailablePluginsResponse) Reset() {
	*x = ListAvailablePluginsResponse{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailablePluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailablePluginsResponse) ProtoMessage() {}

func (x *ListAvailablePluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailablePluginsResponse.ProtoReflect.Descriptor instead.
func (*ListAvailablePluginsResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{2}
}

func (x *ListAvailablePluginsResponse) GetPlugins() []*PluginProvider {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type InitiateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderId    string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateLinkRequest) Reset() {
	*x = InitiateLinkRequest{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateLinkRequest) ProtoMessage() {}

func (x *InitiateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateLinkRequest.ProtoReflect.Descriptor instead.
func (*InitiateLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{3}
}

func (x *InitiateLinkRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

type InitiateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	AuthMethod    string                 `protobuf:"bytes,2,opt,name=auth_method,json=authMethod,proto3" json:"auth_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateLinkResponse) Reset() {
	*x = InitiateLinkResponse{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateLinkResponse) ProtoMessage() {}

func (x *InitiateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateLinkResponse.ProtoReflect.Descriptor instead.
func (*InitiateLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{4}
}

func (x *InitiateLinkResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

func (x *InitiateLinkResponse) GetAuthMethod() string {
	if x != nil {
		return x.AuthMethod
	}
	return ""
}

type CompleteFirebaseLinkRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProviderId          string                 `protobuf:"bytes,1,opt,name=provider_id,json=providerId,proto3" json:"provider_id,omitempty"`
	ProviderAccessToken string                 `protobuf:"bytes,2,opt,name=provider_access_token,json=providerAccessToken,proto3" json:"provider_access_token,omitempty"`
	ProviderIdToken     string                 `protobuf:"bytes,3,opt,name=provider_id_token,json=providerIdToken,proto3" json:"provider_id_token,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CompleteFirebaseLinkRequest) Reset() {
	*x = CompleteFirebaseLinkRequest{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFirebaseLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFirebaseLinkRequest) ProtoMessage() {}

func (x *CompleteFirebaseLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFirebaseLinkRequest.ProtoReflect.Descriptor instead.
func (*CompleteFirebaseLinkRequest) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteFirebaseLinkRequest) GetProviderId() string {
	if x != nil {
		return x.ProviderId
	}
	return ""
}

func (x *CompleteFirebaseLinkRequest) GetProviderAccessToken() string {
	if x != nil {
		return x.ProviderAccessToken
	}
	return ""
}

func (x *CompleteFirebaseLinkRequest) GetProviderIdToken() string {
	if x != nil {
		return x.ProviderIdToken
	}
	return ""
}

type CompleteFirebaseLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FirebaseUid   string                 `protobuf:"bytes,2,opt,name=firebase_uid,json=firebaseUid,proto3" json:"firebase_uid,omitempty"`
	LinkedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=linked_at,json=linkedAt,proto3" json:"linked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFirebaseLinkResponse) Reset() {
	*x = CompleteFirebaseLinkResponse{}
	mi := &file_api_music_v1_provider_link_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFirebaseLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFirebaseLinkResponse) ProtoMessage() {}

func (x *CompleteFirebaseLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_music_v1_provider_link_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFirebaseLinkResponse.ProtoReflect.Descriptor instead.
func (*CompleteFirebaseLinkResponse) Descriptor() ([]byte, []int) {
	return file_api_music_v1_provider_link_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteFirebaseLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteFirebaseLinkResponse) GetFirebaseUid() string {
	if x != nil {
		return x.FirebaseUid
	}
	return ""
}

func (x *CompleteFirebaseLinkResponse) GetLinkedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LinkedAt
	}
	return nil
}

var File_api_music_v1_provider_link_proto protoreflect.FileDescriptor

const file_api_music_v1_provider_link_proto_rawDesc = "" +
	"\n" +
	" api/music/v1/provider_link.proto\x12\bmusic.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x01\n" +
	"\x0ePluginProvider\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.music.v1.PluginStatusR\x06status\"\x1d\n" +
	"\x1bListAvailablePluginsRequest\"R\n" +
	"\x1cListAvailablePluginsResponse\x122\n" +
	"\aplugins\x18\x01 \x03(\v2\x18.music.v1.PluginProviderR\aplugins\"6\n" +
	"\x13InitiateLinkRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\"R\n" +
	"\x14InitiateLinkResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\x12\x1f\n" +
	"\vauth_method\x18\x02 \x01(\tR\n" +
	"authMethod\"\x9e\x01\n" +
	"\x1bCompleteFirebaseLinkRequest\x12\x1f\n" +
	"\vprovider_id\x18\x01 \x01(\tR\n" +
	"providerId\x122\n" +
	"\x15provider_access_token\x18\x02 \x01(\tR\x13providerAccessToken\x12*\n" +
	"\x11provider_id_token\x18\x03 \x01(\tR\x0fproviderIdToken\"\x94\x01\n" +
	"\x1cCompleteFirebaseLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\ffirebase_uid\x18\x02 \x01(\tR\vfirebaseUid\x127\n" +
	"\tlinked_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blinkedAt*y\n" +
	"\fPluginStatus\x12\x1d\n" +
	"\x19PLUGIN_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PLUGIN_STATUS_READY\x10\x01\x12\x18\n" +
	"\x14PLUGIN_STATUS_LINKED\x10\x02\x12\x17\n" +
	"\x13PLUGIN_STATUS_ERROR\x10\x032\xb2\x02\n" +
	"\x13ProviderLinkService\x12e\n" +
	"\x14ListAvailablePlugins\x12%.music.v1.ListAvailablePluginsRequest\x1a&.music.v1.ListAvailablePluginsResponse\x12M\n" +
	"\fInitiateLink\x12\x1d.music.v1.InitiateLinkRequest\x1a\x1e.music.v1.InitiateLinkResponse\x12e\n" +
	"\x14CompleteFirebaseLink\x12%.music.v1.CompleteFirebaseLinkRequest\x1a&.music.v1.CompleteFirebaseLinkResponseB-Z+github.com/gg582/gozik/api/music/v1;musicv1b\x06proto3"

var (
	file_api_music_v1_provider_link_proto_rawDescOnce sync.Once
	file_api_music_v1_provider_link_proto_rawDescData []byte
)

func file_api_music_v1_provider_link_proto_rawDescGZIP() []byte {
	file_api_music_v1_provider_link_proto_rawDescOnce.Do(func() {
		file_api_music_v1_provider_link_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_music_v1_provider_link_proto_rawDesc), len(file_api_music_v1_provider_link_proto_rawDesc)))
	})
	return file_api_music_v1_provider_link_proto_rawDescData
}

var file_api_music_v1_provider_link_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_music_v1_provider_link_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_music_v1_provider_link_proto_goTypes = []any{
	(PluginStatus)(0),                    // 0: music.v1.PluginStatus
	(*PluginProvider)(nil),               // 1: music.v1.PluginProvider
	(*ListAvailablePluginsRequest)(nil),  // 2: music.v1.ListAvailablePluginsRequest
	(*ListAvailablePluginsResponse)(nil), // 3: music.v1.ListAvailablePluginsResponse
	(*InitiateLinkRequest)(nil),          // 4: music.v1.InitiateLinkRequest
	(*InitiateLinkResponse)(nil),         // 5: music.v1.InitiateLinkResponse
	(*CompleteFirebaseLinkRequest)(nil),  // 6: music.v1.CompleteFirebaseLinkRequest
	(*CompleteFirebaseLinkResponse)(nil), // 7: music.v1.CompleteFirebaseLinkResponse
	(*timestamppb.Timestamp)(nil),        // 8: google.protobuf.Timestamp
}
var file_api_music_v1_provider_link_proto_depIdxs = []int32{
	0, // 0: music.v1.PluginProvider.status:type_name -> music.v1.PluginStatus
	1, // 1: music.v1.ListAvailablePluginsResponse.plugins:type_name -> music.v1.PluginProvider
	8, // 2: music.v1.CompleteFirebaseLinkResponse.linked_at:type_name -> google.protobuf.Timestamp
	2, // 3: music.v1.ProviderLinkService.ListAvailablePlugins:input_type -> music.v1.ListAvailablePluginsRequest
	4, // 4: music.v1.ProviderLinkService.InitiateLink:input_type -> music.v1.InitiateLinkRequest
	6, // 5: music.v1.ProviderLinkService.CompleteFirebaseLink:input_type -> music.v1.CompleteFirebaseLinkRequest
	3, // 6: music.v1.ProviderLinkService.ListAvailablePlugins:output_type -> music.v1.ListAvailablePluginsResponse
	5, // 7: music.v1.ProviderLinkService.InitiateLink:output_type -> music.v1.InitiateLinkResponse
	7, // 8: music.v1.ProviderLinkService.CompleteFirebaseLink:output_type -> music.v1.CompleteFirebaseLinkResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_music_v1_provider_link_proto_init() }
func file_api_music_v1_provider_link_proto_init() {
	if File_api_music_v1_provider_link_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_music_v1_provider_link_proto_rawDesc), len(file_api_music_v1_provider_link_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_music_v1_provider_link_proto_goTypes,
		DependencyIndexes: file_api_music_v1_provider_link_proto_depIdxs,
		EnumInfos:         file_api_music_v1_provider_link_proto_enumTypes,
		MessageInfos:      file_api_music_v1_provider_link_proto_msgTypes,
	}.Build()
	File_api_music_v1_provider_link_proto = out.File
	file_api_music_v1_provider_link_proto_goTypes = nil
	file_api_music_v1_provider_link_proto_depIdxs = nil
}
