// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/music/v1/provider_link.proto

package musicv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProviderLinkService_ListAvailablePlugins_FullMethodName = "/music.v1.ProviderLinkService/ListAvailablePlugins"
	ProviderLinkService_InitiateLink_FullMethodName         = "/music.v1.ProviderLinkService/InitiateLink"
	ProviderLinkService_CompleteFirebaseLink_FullMethodName = "/music.v1.ProviderLinkService/CompleteFirebaseLink"
)

// ProviderLinkServiceClient is the client API for ProviderLinkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProviderLinkServiceClient interface {
	ListAvailablePlugins(ctx context.Context, in *ListAvailablePluginsRequest, opts ...grpc.CallOption) (*ListAvailablePluginsResponse, error)
	InitiateLink(ctx context.Context, in *InitiateLinkRequest, opts ...grpc.CallOption) (*InitiateLinkResponse, error)
	CompleteFirebaseLink(ctx context.Context, in *CompleteFirebaseLinkRequest, opts ...grpc.CallOption) (*CompleteFirebaseLinkResponse, error)
}

type providerLinkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProviderLinkServiceClient(cc grpc.ClientConnInterface) ProviderLinkServiceClient {
	return &providerLinkServiceClient{cc}
}

func (c *providerLinkServiceClient) ListAvailablePlugins(ctx context.Context, in *ListAvailablePluginsRequest, opts ...grpc.CallOption) (*ListAvailablePluginsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAvailablePluginsResponse)
	err := c.cc.Invoke(ctx, ProviderLinkService_ListAvailablePlugins_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerLinkServiceClient) InitiateLink(ctx context.Context, in *InitiateLinkRequest, opts ...grpc.CallOption) (*InitiateLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateLinkResponse)
	err := c.cc.Invoke(ctx, ProviderLinkService_InitiateLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerLinkServiceClient) CompleteFirebaseLink(ctx context.Context, in *CompleteFirebaseLinkRequest, opts ...grpc.CallOption) (*CompleteFirebaseLinkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteFirebaseLinkResponse)
	err := c.cc.Invoke(ctx, ProviderLinkService_CompleteFirebaseLink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderLinkServiceServer is the server API for ProviderLinkService service.
// All implementations must embed UnimplementedProviderLinkServiceServer
// for forward compatibility.
type ProviderLinkServiceServer interface {
	ListAvailablePlugins(context.Context, *ListAvailablePluginsRequest) (*ListAvailablePluginsResponse, error)
	InitiateLink(context.Context, *InitiateLinkRequest) (*InitiateLinkResponse, error)
	CompleteFirebaseLink(context.Context, *CompleteFirebaseLinkRequest) (*CompleteFirebaseLinkResponse, error)
	mustEmbedUnimplementedProviderLinkServiceServer()
}

// UnimplementedProviderLinkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProviderLinkServiceServer struct{}

func (UnimplementedProviderLinkServiceServer) ListAvailablePlugins(context.Context, *ListAvailablePluginsRequest) (*ListAvailablePluginsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAvailablePlugins not implemented")
}
func (UnimplementedProviderLinkServiceServer) InitiateLink(context.Context, *InitiateLinkRequest) (*InitiateLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateLink not implemented")
}
func (UnimplementedProviderLinkServiceServer) CompleteFirebaseLink(context.Context, *CompleteFirebaseLinkRequest) (*CompleteFirebaseLinkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteFirebaseLink not implemented")
}
func (UnimplementedProviderLinkServiceServer) mustEmbedUnimplementedProviderLinkServiceServer() {}
func (UnimplementedProviderLinkServiceServer) testEmbeddedByValue()                             {}

// UnsafeProviderLinkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProviderLinkServiceServer will
// result in compilation errors.
type UnsafeProviderLinkServiceServer interface {
	mustEmbedUnimplementedProviderLinkServiceServer()
}

func RegisterProviderLinkServiceServer(s grpc.ServiceRegistrar, srv ProviderLinkServiceServer) {
	// If the following call panics, it indicates UnimplementedProviderLinkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProviderLinkService_ServiceDesc, srv)
}

func _ProviderLinkService_ListAvailablePlugins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailablePluginsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderLinkServiceServer).ListAvailablePlugins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderLinkService_ListAvailablePlugins_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderLinkServiceServer).ListAvailablePlugins(ctx, req.(*ListAvailablePluginsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderLinkService_InitiateLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderLinkServiceServer).InitiateLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderLinkService_InitiateLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderLinkServiceServer).InitiateLink(ctx, req.(*InitiateLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProviderLinkService_CompleteFirebaseLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteFirebaseLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderLinkServiceServer).CompleteFirebaseLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProviderLinkService_CompleteFirebaseLink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderLinkServiceServer).CompleteFirebaseLink(ctx, req.(*CompleteFirebaseLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProviderLinkService_ServiceDesc is the grpc.ServiceDesc for ProviderLinkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProviderLinkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "music.v1.ProviderLinkService",
	HandlerType: (*ProviderLinkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAvailablePlugins",
			Handler:    _ProviderLinkService_ListAvailablePlugins_Handler,
		},
		{
			MethodName: "InitiateLink",
			Handler:    _ProviderLinkService_InitiateLink_Handler,
		},
		{
			MethodName: "CompleteFirebaseLink",
			Handler:    _ProviderLinkService_CompleteFirebaseLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/music/v1/provider_link.proto",
}
